### ISSUE TITLE
API improvements

### ISSUE THREAD

**Issue by dmacnet** [mosquito/aio-pika#1]
Interesting looking project! Any plans to port over the improvements you've made in the simple pika asyncio adapter in pull request 768, such as using a pika Credentials object in connect() and saving the basic consumer tag to support canceling it when shutting down? This future-based API is more pleasant to work with.

**Comment by mosquito** [comment]
I have no time for this right now. If you want it right now, you can create a pull request. PR 768 actually not ready yet.

**Comment by mosquito** [comment]
@dmacnet is this issue are actual?

1. The PR based on [#768](https://github.com/pika/pika/pull/805) is merged.
2. pika's v0.11 already [contain an asyncio adapter](http://pika.readthedocs.io/en/0.11.0/version_history.html)
3. Other API features are totally irrelevant to the current pika's API design.
