### ISSUE TITLE
Cluster connection

### ISSUE THREAD

**Issue by luup2k** [mosquito/aio-pika#104]
Hi all,

Looking into doc/classes seems that is not possible connect to a cluster(a,b,c nodes) using aio-pika library.

But... i was thinking about the option to using the add_connection_lost_callback, to regenerate host string, and using other different host, this is possible??

regards

**Comment by mosquito** [comment]
I perform this with round-robin dns. You might register multiple A-records with different addresses. It's more maintainable then change service configuration I guess.

BTW: The best solution for me, it's an install the `consul` with TCP-port health checks. Using dnsmasq I forwarding `.consul` zone and configuring a service to the `amqp://user:password@amqp.service.consul/vhost`.
