### ISSUE TITLE
declare_exchange() documentation

### ISSUE THREAD

**Issue by anomit** [mosquito/aio-pika#111]
First of all, wonderful work in creating the docs. 

Just had a couple of things that I found out:

1. The channel object's documentation at https://aio-pika.readthedocs.io/en/latest/apidoc.html#aio_pika.Channel has no reference to the declare_exchange() method

2. In the examples provided, we don't see a mention of `durable` parameter being passed to `channel_obj.declare_exchange()` . I found it out while playing around with a python publisher and a node.js consumer which somehow set different defaults for the channel and the python publisher failed at the declare_exchange repeatedly with the following error:
`pika.exceptions.ChannelClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'web' in vhost '/': received 'false' but current is 'true'")`

What worked is changing my python exchange declaration to:
`self.__exchange = await self._rmq_channel.declare_exchange('web', aio_pika.ExchangeType.DIRECT, durable=True)`

**Comment by mosquito** [comment]
@anomit now is all proper when I can see.
