### ISSUE TITLE
Can I use aio-pika in twisted? Is there an example?

### ISSUE THREAD

**Issue by quanjin9099** [mosquito/aio-pika#115]
Can I use aio-pika in twisted? Is there an example?
ths

**Comment by decaz** [comment]
`aio-pika` is for `asyncio` only. Use `pika` instead (look at http://pika.readthedocs.io/en/0.11.2/modules/adapters/twisted.html).

**Comment by tobiasfielitz** [comment]
@quanjin9099 use [asyncio](https://docs.python.org/3/library/asyncio.html) with aio-pika. Don't use twisted if possible. :-)

**Comment by decaz** [comment]
@quanjin9099 @mosquito I guess this can be closed.
