### ISSUE TITLE
pip install latest aio pika with bad pika version

### ISSUE THREAD

**Issue by nirtayeb** [mosquito/aio-pika#118]
I tried to install latest aio-pika with those commands:
`pip install aio-pika`
`pip install https://github.com/mosquito/aio-pika/archive/2.3.0.tar.gz`
and, `pip install https://github.com/mosquito/aio-pika/archive/2.3.0.zip`

All of the three installed pika-0.11.2 instead of pika-0.10.0

but if I use:
`pip install git+https://github.com/mosquito/aio-pika`

it installs the pika-0.10.0

**Comment by mosquito** [comment]
The 2.4.0 just released.
