### ISSUE TITLE
Need to close the channel explicitly?

### ISSUE THREAD

**Issue by imnisen** [mosquito/aio-pika#121]
Hi，When the publisher successfully publish a message, does it need to close the declared channel explicitly?   As shows below:

```
async def publish(data):
       # Here conn is global,made by "connect_robust", which I want to make it long live
        channel = await conn.channel()  
        exchange = await channel.declare_exchange(
            'some_exchange',
            aio_pika.ExchangeType.DIRECT,
            durable=True
        )
        message = aio_pika.Message(
            json.dumps(data).encode(),
            headers={"a": "b")},
            delivery_mode=aio_pika.DeliveryMode.PERSISTENT
        )
        await exchange.publish(message, routing_key="some_key")
        await channel.close()  # Need close here?
```

I want to reuse the connection, so make it global, after that, each time when I need publish a message, I declare the channel, send the message, the close the channel.

My problem is if I close the channel with `await channel.close()`, when call the method `publish` frequently(0.5 second once), this will raise a `pika.exceptions.ChannelClosed`, not each time, several times one exception could happen.
This is very strange, because the channel each time is a new channel, not the closed one last time.

However, if I don't close the channel myself, this works ok.

What cause this problem, or is there another good practise for this.

ps:  aio-pika ==2.3.0, python==3.6.2

Thanks very much!

**Comment by finetuned89** [comment]
I am experiencing this exact issue. After a few messages have been sent, aio-pika will raise an Exception was never retrieved error:

```
Task exception was never retrieved
future: <Task finished coro=<Channel.close() done, defined at /home/gitlab-runner/integration-tests/python_env/lib/python3.6/site-packages/aio_pika/common.py:116> exception=The channel was closed: ()>
Traceback (most recent call last):
  File "/home/gitlab-runner/integration-tests/python_env/lib/python3.6/site-packages/aio_pika/common.py", line 120, in wrap
    raise exceptions.ChannelClosed
pika.exceptions.ChannelClosed

```

It is also impossible to catch this error, if I use:

```
try:
    await my_channel.close()
except Exception as e:
    print("Cannot close channel")  # This is never reached
```

If I don't explicitely close the channels, the number of channels on RabbitMQ keeps growing, which is undesireable. If I do close the channel explicitly, the code keeps working, but the `Task exception was never retrieved` show up.

**Comment by dan-stone** [comment]
The exception is originating from Channel's __del__ method, i.e.

```
# aio-pika/channel.py
# line 335
def __del__(self):
    with suppress(Exception):
        self.loop.create_task(self.close())
```

What happens is if a channel has been explicitly closed with a call to `close()`, the exception will be raised whenever the above `__del__` method is invoked (i.e. the object is garbage collected) - the future returned by `self.loop.create_task(self.close())` is left hanging, and we get a cryptic error message from asyncio that nothing has handled the exception.

It is generally considered bad practice to utilize __del__ for resource cleanup (some discussion around that topic can be found here: https://stackoverflow.com/questions/6104535/i-dont-understand-this-python-del-behaviour) - instead, to achieve implicit channel cleanup, I'm of the opinion channels should be available using an asynchronous context manager, i.e.

```
async with connection.channel() as channel:
    # Do something with the channel
# Channel object has been discarded, and explicitly closed
```

If a channel object has been retrieved without using a context manager, then it is the developers responsibility to explicitly close it when it is no longer needed.

**Comment by mosquito** [comment]
Fixed in aio-pika `2.8.3`

**Comment by dan-stone** [comment]
I've offered a separate [pull request][#130] to add asynchronous context manager support, and remove the `__del__` method on a channel for resource cleanup

**Comment by finetuned89** [comment]
Dan, yours is a much better solution to this problem, and I think you pinpointed the actual location of this Exception. In my testing, my fix also seemed to get rid of the problem, but I have now noticed that it introduces different problems (apparently they were not caught in the automatic tests here either). **My pull request should be reverted**, and I suggest we use Dan's solution here.

Sorry about this.
