### ISSUE TITLE
DeprecationWarning with RobustQueue with example code and python 3.6

### ISSUE THREAD

**Issue by taybin** [mosquito/aio-pika#126]
Using the example code and python 3.6, I get this message in my logs:
> DeprecationWarning: 'RobustQueue' implements legacy `__aiter__` protocol;`__aiter__` should return an asynchronous iterator, not awaitable
  `async for message in queue:`

I'm running aio-pika 2.7.1.

**Comment by mosquito** [comment]
Is it still actual?

**Comment by taybin** [comment]
I'm not sure.  Going to close.
