### ISSUE TITLE
Incorrect type annotation for return value in RobustConnection.channel() 

### ISSUE THREAD

**Issue by dangusev** [mosquito/aio-pika#137]
Hey! It seems that after latest changes in .channel() method API somebody forgot to update the type annotation) Now it's not a coroutine and just returns Channel instance.

https://github.com/mosquito/aio-pika/blob/5aa024141a18355306aed504fc09e6244a6601cf/aio_pika/connection.py#L230

**Comment by mosquito** [comment]
This returns just created but not initialized channel. For initialization you should call and await the `__iter__` (`__await__` for Py3.5+) on just created channel instance. For Python 3.4 I have to use `Coroutine` type notation instead `Awaitable` type.
