### ISSUE TITLE
Can't connect.

### ISSUE THREAD

**Issue by mawaishanif** [mosquito/aio-pika#157]
`Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    asyncio.run(acon())
  File "C:\Users\Awais\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Awais\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "<pyshell#5>", line 2, in acon
    return await aio_pika.connect("AMPQ URL")
  File "C:\Users\Awais\AppData\Local\Programs\Python\Python37\lib\site-packages\aio_pika\connection.py", line 437, in connect
    await connection.connect()
  File "C:\Users\Awais\AppData\Local\Programs\Python\Python37\lib\site-packages\aio_pika\connection.py", line 232, in connect
    result = await f
ConnectionRefusedError: Connection to 35.183.159.128:5672 failed: timeout
>>> 
`

Here is my function
async def acon():
	return await aio_pika.connect("URL")

*I have changed url and ip to dummy ones.*

I can connect to locally hosted rabbitMQ server but when I connect to external server I see this error.

**Comment by mosquito** [comment]
You pass an invalid URL I guess. Pass the connection URL in this format:

```amqp://{username}:{password}@{host}:{port}/{vhost}```

**Comment by mosquito** [comment]
As I can see you have 35.183.159.128 on Amazon Cloud. Did you check the firewall settings?

**Comment by mawaishanif** [comment]
"amqp://username:passwordB@host/vhost"

I am using this format and my username and vhost are same.
But there is missing port.

Let me try the format you have given me. And thanks for quick response.

URL is dummy one but I am on Amazon Cloud.

**Comment by mawaishanif** [comment]
I am still getting the same error, here is the actual URL "amqp://wvekznkq:password@mustang.rmq.cloudamqp.com/wvekznkq"

**Comment by mosquito** [comment]
Could you try to connect using `telnet 35.183.159.128 5672`?

**Comment by mawaishanif** [comment]
Maybe something is wrong with cmd promopt/powershell in windows. It does not give any response. But the blank screen I get after typing this cmd allows me to type something, and when i type randomly it says connection to host lost.

And if i change input it straight away gives the error. And I also tried cmd localhost 5000 on simple flask app same blank screen appear but when I type randomly in it it gives response back in html.

**Comment by mawaishanif** [comment]
After initial command.

It also shows a message "Connecting to 35.189.189.198 5672" but it disappear quickly.
![cap1](https://user-images.githubusercontent.com/20681953/47561758-a59faf80-d935-11e8-8187-b223a7416fe3.JPG)

After I type randomly.

![cap2](https://user-images.githubusercontent.com/20681953/47561770-aa646380-d935-11e8-962e-72eeee15af6e.JPG)

**Comment by mawaishanif** [comment]
I think the problem is with my computer. Library does not have to do anything with it. I tried it on https://repl.it and it worked fine.

**Comment by dev0Guy** [comment]
I've the sane error. Pika for me and aio-pika just fail. I using ssl with context
