### ISSUE TITLE
Raise `DeprecationWarning` by using python3.7.1

### ISSUE THREAD

**Issue by linw1995** [mosquito/aio-pika#159]
It raise `DeprecationWarning` by using **python3.7.1**

```
/aio_pika/pika/utils.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return isinstance(handle, collections.Callable)
```

https://github.com/mosquito/aio-pika/blob/ca6b3d2bec562a0d6853dfd50c671fa487c7c425/aio_pika/pika/utils.py#L16

**Comment by decaz** [comment]
@linw1995 @mosquito I guess this can be closed as it was resolved in #153.
