### ISSUE TITLE
Question: What is the best channel management strategy

### ISSUE THREAD

**Issue by krieghan** [mosquito/aio-pika#173]
I'm struggling with the discovering the best strategy for channel management in a web application that uses aio_pika to publish to a RabbitMQ queue, and I'm hoping that you have some insights into this.  I've looked for information in the documentation, and in other issues for such insights, but I haven't been able to find an authoritative answer to my question.  Here are the options that I've come up with:

1. Create a new channel each time a task needs to publish to the queue, using a context manager.  The channel should be torn down after the task publishes.

(This seems wasteful, as we end up creating a lot of ephemeral channels and the associated exchanges, whose lifetime is very limited)

2. Create a single global channel that every task uses for publishing

3. Create a channel pool (with some min and max number of channels).  Each channel can only be used by one task at a time.

4. Create a channel pool (as above, in 3), but allow each channel to be used by multiple tasks.  The pool should distribute work evenly to all the channels.  Perhaps there should be some ceiling on how many tasks can be publishing on each channel, but perhaps not.

I know that a channel *can* be used by multiple tasks at the same time.  I think the main thing that I do not understand is if there is some performance benefit of having multiple channels, or some maximum number of communications that a channel can be engaged in simultaneously.  Documentation for Rabbit and AMQP and various discussions about channels seem to revolve around having one channel-per-thread, but I'm not quite sure how that applies to use in aio applications.

**Comment by mosquito** [comment]
@krieghan I preparing to merge #174. When you have any comments feel free to write it there.

**Comment by krieghan** [comment]
Wow, I didn't expect an actual implementation.  Thanks!
