### ISSUE TITLE
ImportError: cannot import name 'AsyncContextManager'

### ISSUE THREAD

**Issue by montag451** [mosquito/aio-pika#188]
The latest version of `aio-pika` available on PyPI (version 4.9.3) fails to load on Python 3.5. `AsyncContextManager` has been introduced in Python 3.6. Is Python 3.5 not supported anymore ?

**Comment by mosquito** [comment]
Could you provide the complete stack trace?

**Comment by montag451** [comment]
> Could you provide the complete stack trace?

```
Python 3.5.3 (default, Dec  5 2018, 17:37:01) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aio_pika
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test/lib/python3.5/site-packages/aio_pika/__init__.py", line 2, in <module>
    from . import pool
  File "/tmp/test/lib/python3.5/site-packages/aio_pika/pool.py", line 3, in <module>
    from typing import Any, AsyncContextManager, Callable, Coroutine, TypeVar
ImportError: cannot import name 'AsyncContextManager'
```

**Comment by dequis** [comment]
Looks like this was added in 3.6.2 and 3.5.4 as part of https://bugs.python.org/issue28556 (relevant github PR are 2076, 2087, 2088)

Both the 3.5 and 3.6 changelogs mention https://docs.python.org/3.6/whatsnew/changelog.html

>bpo-28556: Updates to typing module: Add generic AsyncContextManager, add support for ContextManager on all versions. Original PRs by Jelle Zijlstra and Ivan Levkivskyi

Weird case, as one would expect distros to update to the latest micro releases within a stable branch.

**Comment by montag451** [comment]
Debian Stretch (the current stable release) provides Python 3.5.3. I don't know if they plan to update it in the near future
