### ISSUE TITLE
Hang at exit, likely due to run_in_executor changes

### ISSUE THREAD

**Issue by dequis** [mosquito/aio-pika#191]
re: https://github.com/mosquito/aio-pika/pull/186

I'm seeing some weird behavior that isn't quite a deadlock, but since it doesn't make sense it's probably threads. Specifically, it happened a few times already that part of my application code would raise an exception and hang. The asyncio runner code has a try...finally loop whose finally clause tries to cancel all running tasks, but it doesn't seem to be able to cancel them, waiting forever instead. Also, since it never leaves the finally, the original exception isn't printed.

My exception happens inside the first run_until_complete of the following part of asyncio:

```python
    try:
        events.set_event_loop(loop)
        loop.set_debug(debug)
        return loop.run_until_complete(main)     # <-------
    finally:
        try:
            _cancel_all_tasks(loop)
            loop.run_until_complete(loop.shutdown_asyncgens())
        finally:
            events.set_event_loop(None)
            loop.close()
```

(from https://github.com/python/cpython/blob/v3.7.2/Lib/asyncio/runners.py )t

Then _cancel_all_tasks gets stuck forever here:

```python
    for task in to_cancel:
        task.cancel()


    loop.run_until_complete(
        tasks.gather(*to_cancel, loop=loop, return_exceptions=True))
```

The traceback for this location is:

```
  File "my_app.py", line 261, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 46, in run
    _cancel_all_tasks(loop)
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 62, in _cancel_all_tasks
    tasks.gather(*to_cancel, loop=loop, return_exceptions=True))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 555, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 523, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1722, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.7/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "<string>", line 1, in <module>
```

This isn't an exception, it's a `traceback.print_stack()` called from an attached gdb, specifically:

```
(gdb) p PyRun_SimpleString("import traceback; traceback.print_stack()")
```

I still haven't found exactly what causes this, and it's likely to be a problem in asyncio, not really here. This is also python 3.7.0 instead of 3.7.2 so maybe some bugfixes are missing. I mostly wanted to write this down somewhere in case it starts hitting other people. And it seems very likely that this is because of the thread pool added by run_in_executor.

**Comment by mosquito** [comment]
@dequis thank you so much for your contribution to the project. Now I’m trying to integrate aiormq into a project for a replacement for pika. I am preparing version 5.0.0 and last thing what I have to integrate to is robust_connect.

aiormq is pure-python amqp 0.9.X implementation with modern python and asyncio.

**Comment by mosquito** [comment]
By the way, after your second post, I think to add optional support for aiodns. 🤔

**Comment by dequis** [comment]
I haven't been able to reproduce the issue again with 4.9.3, but 5.x is doing the right thing now, so, yay.
