### ISSUE TITLE
rabbitmqctl list_queues via aio-pika

### ISSUE THREAD

**Issue by vgoklani** [mosquito/aio-pika#194]
Hello - how would i replicate the results of "rabbitmqctl list_queues" via aio-pika?

Thanks!

**Comment by NathanUrwin** [comment]
Hey @vgoklani 👋 

AFAIK (as far as I know) this is not possible with `aio-pika` or even `pika` either.

See [here](https://stackoverflow.com/questions/4287941/how-can-i-list-or-discover-queues-on-a-rabbitmq-exchange-using-python) for more info. Good luck to you!

**Comment by mosquito** [comment]
Protocol AMQP 0.9.x doesn't provide any method to list queues.
