### ISSUE TITLE
Callbacks were gone

### ISSUE THREAD

**Issue by decaz** [mosquito/aio-pika#200]
There are no more `add_connection_lost_callback` and `add_reconnect_callback` callbacks for connection.

**Comment by mosquito** [comment]
`add_reconnect_callback` still [here](https://github.com/mosquito/aio-pika/blob/master/aio_pika/robust_connection.py#L66) and available only for` RobustConnection`.

`add_connection_lost_callback` it's a lost breaking change from `CHANGELOG.md`. Now it's [`add_close_callback`](https://github.com/mosquito/aio-pika/blob/master/aio_pika/connection.py#L67) method available for both connection types.

**Comment by decaz** [comment]
Ok, thanks!
