### ISSUE TITLE
yarl exception when connecting

### ISSUE THREAD

**Issue by decaz** [mosquito/aio-pika#201]
If virtualhost is specified explicitly (not `/`), then yarl raises `ValueError: Path in a URL with authority should start with a slash ('/') if set`:
https://github.com/aio-libs/yarl/blob/948f9c2df5a40a7a59e4bea3901bdd537d984b28/tests/test_url_build.py#L166-L168

**Comment by mosquito** [comment]
Oh, my mistake. Will be fixed in `aiormq` today.

**Comment by mosquito** [comment]
fixed in `aiormq==2.0.0`

**Comment by mosquito** [comment]
Fixed in `aio-pika==5.3.0`

**Comment by decaz** [comment]
@mosquito I have installed
```
aiormq==2.0.1
aio-pika==5.3.2
pamqp==2.1.0
yarl==1.3.0
```
but the problem still exists.

**Comment by decaz** [comment]
Here is the script to reproduce the bug:
```python
import asyncio
import aio_pika

async def main():
    await aio_pika.connect_robust(virtualhost='test')

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```
