### ISSUE TITLE
Headers value type forced to str

### ISSUE THREAD

**Issue by Artimi** [mosquito/aio-pika#209]
Hi,

Thanks for the work you are doing on `aio_pika` lately. Much appreciated.

I've noticed that with the new major version all headers values are cast to `str` see:
```python
>>> import aio_pika
>>> m = aio_pika.Message(b'hello', headers = {'int': 42})
>>> m.headers['int'] == 42
False
>>> type(m.headers['int'])
str
```
Is this intentional? I can see it is probably because of https://github.com/mosquito/aio-pika/blob/master/aio_pika/message.py#L164. What is the reason behind this? We are sending ints in headers so this blocks us from update to current `aio_pika`.

**Comment by mosquito** [comment]
Yes. It's a bug.

**Comment by mosquito** [comment]
Could you please describe your cases [here](https://github.com/mosquito/aio-pika/pull/211/files#diff-3c7fac459f9ff713e30df0d7d0ae00ceR1505)

**Comment by Artimi** [comment]
I think the fix is sufficient. Thanks, @mosquito!
