### ISSUE TITLE
Exception in Queue.consume callback isn't propagated properly

### ISSUE THREAD

**Issue by kremius** [mosquito/aio-pika#216]
``` python
def foo(m):
    print('exception will be raised')
    raise ValueError('error')

await queue.consume(foo)
```
And then a new message is received from RabbitMQ.

**Expected behavior:** `asyncio` exception handler is called immediately.
**Actual behavior**: exception is placed into future and then that future is abandoned. When future's `__del__` will be called it will call loop exception handler.

I assume that happens because here https://github.com/mosquito/aio-pika/blob/master/aio_pika/tools.py#L31 callback call is wrapped into `run` function which places raised exception into future, but seems like that future is never handled afterwards.
I "fixed" that issue locally by removing exception handling:
```python
# try:
future.set_result(func(*args, **kwargs))
# except Exception as e:
#     future.set_exception(e)
```
but I'm not sure that it's really good fix.

If it's expected behavior then can you hint how to properly handle exceptions in such cases?
Thanks

**Comment by mosquito** [comment]
Please test `aio-pika==5.5.2`.

**Comment by kremius** [comment]
Works like a charm, thanks a lot.
