### ISSUE TITLE
Tutorial connection string does not work on MacOS

### ISSUE THREAD

**Issue by pearsonhenri** [mosquito/aio-pika#220]
Howdy folks,

Was just going through the [RabbitMQ tutorial](https://aio-pika.readthedocs.io/en/latest/rabbitmq-tutorial/1-introduction.html) and ran into problems initiating a connection as follows:
```
    # Perform connection
    connection = await connect(
        "amqp://guest:guest@localhost/", loop=loop
    )
```
Unclear why, but `localhost` is not resolving to `127.0.0.1` with this lib. If I replace it with `127.0.0.1`, things start working out ¯\_(ツ)_/¯ 

Not immediately clear to me why this would be the case by looking at the [code base](https://github.com/mosquito/aio-pika/blob/master/aio_pika/connection.py#L207), but just wanted to point out this papercut that I ran into. Thanks folks!

**Comment by mosquito** [comment]
I am back from my vacation, and now I returning to the accumulated requests and issues. Thanks for your contribution. I will return with answer as soon as possible.
