### ISSUE TITLE
Question: What is the best way to cleanly close a pool of channels

### ISSUE THREAD

**Issue by pappachino** [mosquito/aio-pika#223]
Hi, 

In most of the documentation, context managers are being used to close channels and connections I believe.
However if I have a connection pool and a channel pool, I would like to cleanly close all the channels and the connections in the pool on shutdown of the app. But seems like there is no wait_closed or close, as in the aiopg package.

Maybe I am missing out something, can you help me out with an example where I can pass a channel pool to a producer and cleanly close all the alive connections and channels.

Thanks.

**Comment by mosquito** [comment]
I am back from my vacation, and now I returning to the accumulated requests and issues. Thanks for your contribution. I will return with answer as soon as possible.

**Comment by inventionlabsSydney** [comment]
@mosquito Any chance of some further information? I am currently getting a client unexpectedly closed TCP connection on rabbitmq side because I'm using connection pools.

**Comment by mosquito** [comment]
now Pool has `close()` method and might be used in async context manager
