### ISSUE TITLE
Question: is it possible to set heartbeat with uri params

### ISSUE THREAD

**Issue by Spacemaan** [mosquito/aio-pika#224]
I have uri string : "amqp://NANA:NANA@localhost:5672/NANA?heartbeat=10"
After i create connection i get only :
amqp://NANA:****@localhost:5672/NANA
and in rabbitmq management i get default value of 60s for heatbeat

Is it possible to set value for heartbeat for this connection ?

**Comment by kremius** [comment]
Should be possible with aiormq >= 2.5.1 (since this one https://github.com/mosquito/aiormq/pull/31)

**Comment by Spacemaan** [comment]
Great, it's working

**Comment by fortunto2** [comment]
Hi, i use 

aio-pika 6.8.0
aiormq  3.3.1
rabbitmq RabbitMQ 3.9.5

```python

async def main():
    print('----------------')
    # Perform connection
    connection = await connect_robust(
        "amqp://user:******@xxxxxxx/vhost?heartbeat=0",
        client_properties={
            'connection_name': 'Worker'
        }, timeout=100
    )
    
    print(connection)
    # Creating a channel
    channel = await connection.channel()
    await channel.set_qos(prefetch_count=1)
    print(channel)

    # Declaring queue
    queue = await channel.declare_queue(
        "task_queue",
        durable=True,
        timeout=100
    )
    print(queue)
    print('----------------')

    # Start listening the queue with name 'task_queue'
    await queue.consume(on_message, no_ack=False)
```

and connection created with heartbeat=60s
Why?
Maybe need update aiormq to 4-5?
