### ISSUE TITLE
QueueIterator and "no_ack"

### ISSUE THREAD

**Issue by decaz** [mosquito/aio-pika#226]
`QueueIterator` should not reject messages on close if it was initialized with `no_ack=True`:
https://github.com/mosquito/aio-pika/blob/83fe1b206022b26d39a70f6a3359d2e6963826e8/aio_pika/queue.py#L366-L370
Otherwise the exception will be raised:
https://github.com/mosquito/aio-pika/blob/83fe1b206022b26d39a70f6a3359d2e6963826e8/aio_pika/message.py#L557-L558

**Comment by mosquito** [comment]
I am back from my vacation, and now I returning to the accumulated requests and issues. Thanks for your contribution. I will return with answer as soon as possible.
