### ISSUE TITLE
No way to use rabbitmq-autogenerated queue name without monkey patching

### ISSUE THREAD

**Issue by misuzu** [mosquito/aio-pika#228]
When setting queue name to '' rabbitmq should generate queue name on its own.
aio-pika is not usable on secured rabbitmq instances:
```python
queue = await self._channel.declare_queue(
            name='',
            auto_delete=True,
            exclusive=True)
```
```
aiormq.exceptions.ChannelAccessRefused: ACCESS_REFUSED - access to queue 'amq_minjshlm3xwhkaaqnfaaqw6jbu' in vhost '****' refused for user '*****'
```

I have to monkey patch RobustQueue to get things working:
```python
aio_pika.robust_queue.RobustQueue._get_random_queue_name = lambda x: ''
```

**Comment by mosquito** [comment]
That’s because connect_robust was applied. RabbitMQ can not allow to declare queue with generated name after reconnecting.

**Comment by misuzu** [comment]
@mosquito why not declare new queue (with name '') in this case?

**Comment by mosquito** [comment]
@misuzu in case when you create temporary queue without auto_delete flag queued and undelivered messages will be forgotten in old temporary queue.

**Comment by misuzu** [comment]
@mosquito this kind of usage can lead to many unused queues if not used right and should be discouraged.
Also aio-pika documentation states than when queue name is not specified it will be generated by server so this behavior contradicts documentation.
https://aio-pika.readthedocs.io/en/latest/rabbitmq-tutorial/3-publish-subscribe.html#temporary-queues

**Comment by mosquito** [comment]
@cloud-rocket just do not use RobustConnection when you not afraid to lost this temporary queue, when non-robust connection is used broker generates a queue name

**Comment by cloud-rocket** [comment]
@mosquito - thanks for a fast reply!

I am not afraid to lose data, but I do expect the reconnection to be handled. I kind of miss the point of RobustConnection, if reconnect causes this exception. 

Can please explain?
