### ISSUE TITLE
RobustChannel will not reconnect if the queue/exchange is declared twice with the same name.

### ISSUE THREAD

**Issue by Darkless012** [mosquito/aio-pika#229]
If you declare exchange for the second time (with the same parameters), it overrides the previous exchange in `self._exchanges[name]` reference, which causes "on_reconnect" not to pass new channel to declared exchanges/queues, resulting in `RuntimeError: <Channel: "1"> closed` errors.

I would make a pull request but don't know what's the correct solution, so I will propose few below:

I will state the examples on **exchanges**, but everything also applies to **queues**

**Option 1 - Fetch exchange from already declared dict**

`robust_channel.py`
```
async def declare_exchange(self, name: str,
                           type: ExchangeType=ExchangeType.DIRECT,
                           durable: bool=None, auto_delete: bool=False,
                           internal: bool=False, passive: bool=False,
                           arguments: dict=None, timeout: int=None,
                           robust: bool=True) -> Exchange:

+   if name in self._exchanges:
+       return self._exchanges[name]

    exchange = await super().declare_exchange(
        name=name, type=type, durable=durable, auto_delete=auto_delete,
        internal=internal, passive=passive, arguments=arguments,
        timeout=timeout,
    )

    if not internal and robust:
        self._exchanges[name] = exchange

    return exchange
```

Cons: 
- You return object which is used elsewhere
- If you declare exchange with different parameters it will silently pass and return current instance, instead of raising exception.

**Option 2 - variance on Option 1**
Actually trying to declare the exchange and discarting fetched object afterward 
`robust_channel.py`
```
async def declare_exchange(self, name: str,
                           type: ExchangeType=ExchangeType.DIRECT,
                           durable: bool=None, auto_delete: bool=False,
                           internal: bool=False, passive: bool=False,
                           arguments: dict=None, timeout: int=None,
                           robust: bool=True) -> Exchange:

    exchange = await super().declare_exchange(
        name=name, type=type, durable=durable, auto_delete=auto_delete,
        internal=internal, passive=passive, arguments=arguments,
        timeout=timeout,
    )

+   if name in self._exchanges:
+       return self._exchanges[name]

    if not internal and robust:
        self._exchanges[name] = exchange

    return exchange
```

Cons: 
- You return object which is used elsewhere
- Discarting awaited object.
- Confusing code without explanation/comments

**Option 3 - Compare all exchange connection parameters**
`robust_channel.py`
```
async def declare_exchange(self, name: str,
                           type: ExchangeType=ExchangeType.DIRECT,
                           durable: bool=None, auto_delete: bool=False,
                           internal: bool=False, passive: bool=False,
                           arguments: dict=None, timeout: int=None,
                           robust: bool=True) -> Exchange:

+   if name in self._exchanges:
+       exchange = self._exchanges[name]
+       if exchange.__type != type or exchange.durable is not durable or ... # rest
+           raise RuntimeException("can't declare exchange... different arguments") 
+       return self._exchanges[name]

    exchange = await super().declare_exchange(
        name=name, type=type, durable=durable, auto_delete=auto_delete,
        internal=internal, passive=passive, arguments=arguments,
        timeout=timeout,
    )

    if not internal and robust:
        self._exchanges[name] = exchange

    return exchange
```

**Option 4 - Store all the created exchanges**

`robust_channel.py`
```
async def declare_exchange(self, name: str,
                           type: ExchangeType=ExchangeType.DIRECT,
                           durable: bool=None, auto_delete: bool=False,
                           internal: bool=False, passive: bool=False,
                           arguments: dict=None, timeout: int=None,
                           robust: bool=True) -> Exchange:

    exchange = await super().declare_exchange(
        name=name, type=type, durable=durable, auto_delete=auto_delete,
        internal=internal, passive=passive, arguments=arguments,
        timeout=timeout,
    )

    if not internal and robust:
+       self._exchanges[(name, id(exchange))] = exchange

    return exchange
```

Cons:
- `exchange_delete` can't be done just by name - since you can have multiple instance with same name 
- OR delete all the references to the exchange with the name, in which case either make self._exchanges[name] = list() for easier delete lookup, but harder to cycle through (2 levels of nesting)

I'm inclined to Option 2 or Option 3, but I'd like to know other opinions or Options.

**Comment by aviramha** [comment]
You plan on creating a PR? I'd like to use your fix :)

**Comment by mosquito** [comment]
Option four looks cool, of course fell free to create PR

**Comment by aviramha** [comment]
@mosquito I think I'll create a PR, and I'm planning to go for 3.
I think if user declares twice the same name with different arguments without deleting the old one they should receive an error.

**Comment by aviramha** [comment]
Seems that my PR was reverted/reformatted. From my very quick check looks like this brought the issue back..
