### ISSUE TITLE
UI friendly connection name, connection_name

### ISSUE THREAD

**Issue by Gyllsdorff** [mosquito/aio-pika#264]
In many rabbitmq client libs it is possible to set a connection name that will be visible in the admin UI, this makes it a bit easier for admins to kill connections abusing the system, debugging, etc.

[This is](https://github.com/pika/pika/issues/989) how it is done in Pika, is it possible to do the same thing in `aio-pika`? I took a look in the code but I couldn't find anything like it.

**Comment by mosquito** [comment]
#265 fixes it.

**Comment by mosquito** [comment]
[See this documentation article](https://aio-pika.readthedocs.io/en/latest/apidoc.html#aio_pika.connect).

**Comment by corsearch-honarkhah** [comment]
I tested it with the latest version it seems it is not working!
