### ISSUE TITLE
update pypi package

### ISSUE THREAD

**Issue by x0day** [mosquito/aio-pika#270]
the current package version in github is 6.3.2, but package version is 6.3.0 in pypi.

install_requires in aio-pika 6.3.0 is 'aiormq>=2.9,<3', so we can't feel aiormq bug is fixed if we install aio-pika use pipenv。

https://github.com/mosquito/aio-pika/commit/64985751afae608344bbc06c85e7a17f796e2d09#diff-2eeaed663bd0d25b7e608891384b7298
https://github.com/mosquito/aiormq/commit/26ffef5978856a58883cc4d99642bee550ad3370

**Comment by mosquito** [comment]
I will made release after #267.

**Comment by mosquito** [comment]
I hope the release will be includes #269

**Comment by x0day** [comment]
@mosquito nice work!
