### ISSUE TITLE
Question: What is the recommended way of consuming and publishing in the same program?

### ISSUE THREAD

**Issue by nockstarr** [mosquito/aio-pika#275]
Im my particular use case I need to  
1. Continuously consume messages from Q1.
2. Process each received message.
3. For each received and processed message a "new message" is created.
4. Publish new message to Q2.   

I could not find many examples on how to do this, but this must be a pretty common use case? "I" came up with this method (mostly borrowed from [Connection pooling example).](https://aio-pika.readthedocs.io/en/latest/quick-start.html#connection-pooling) I feel like it must be a better way to do this ?

```python
import asyncio
import aio_pika
from aio_pika.pool import Pool
import json

RABBIT_URI = "amqp://guest:guest@localhost/"

CONSUMER_QUEUE = "processing_queue"
EXCHANGE_NAME = "completed_alerts"
PUBLISH_QUEUE = "completed_queue"


async def main_tester():
    """Everything creating inside main_tester() for simplicity of this example"""
    loop = asyncio.get_event_loop()

    async def get_connection():
        return await aio_pika.connect_robust(RABBIT_URI)

    connection_pool = Pool(get_connection, max_size=2, loop=loop)

    async def get_channel() -> aio_pika.Channel:
        async with connection_pool.acquire() as connection:
            return await connection.channel()

    channel_pool = Pool(get_channel, max_size=10, loop=loop)

    async def consume():
        async with channel_pool.acquire() as channel:  # type: aio_pika.Channel
            while True:
                await channel.set_qos(10)

                queue = await channel.declare_queue(
                    CONSUMER_QUEUE,
                    durable=True,
                    auto_delete=False
                )
                async with queue.iterator() as queue_iter:
                    async for message in queue_iter:
                        msg = json.loads(message.body)
                        # Do a lot of stuff with the received message..
                        # When the 'processing' of the received process is done, a new message is created which needs
                        # to be published to another queue.
                        new_message = {"msg": "Represents a new message as a result of processing the received message"}

                        await publish(new_message, PUBLISH_QUEUE)
                        await message.ack()
                await asyncio.sleep(0.1)

    async def publish(msg: dict, routing_key: str):
        async with channel_pool.acquire() as channel:  # type: aio_pika.Channel
            exchange = await channel.declare_exchange(EXCHANGE_NAME, durable=True)

            ready_queue = await channel.declare_queue(
                routing_key, durable=True
            )
            await ready_queue.bind(exchange, routing_key)

            await exchange.publish(
                aio_pika.Message(
                    body=json.dumps(msg).encode(),
                    delivery_mode=aio_pika.DeliveryMode.PERSISTENT
                ),
                routing_key
            )

    task = loop.create_task(consume())
    await task

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main_tester())
    loop.close()
```

**Comment by mosquito** [comment]
You may use a single channel from the single connection for this example actually because you don't use transactions you might use one channel for consuming and publishing. If you want to use transactions create the second channel for transactional publishing. So in general case, the two channels are enough.

Of course when you have to split QoS settings for different queues or other channel-specific features you might create as much as necessary channels, but not greater than 2048 (by default) at the same time.

In case your RabbitMQ cluster contains eleven nodes for example and message rate over 5k messages per second load balancing via connection pool are justified otherwise it's like using a cannon to kill a fly.

My recommendation is to use two channels first for reading (consuming) second for writing (publishing) by default.

**Comment by nockstarr** [comment]
Thanks for a great answer

**Comment by durgeksh** [comment]
@nockstarr could you please post full code here. I am also in need of same. My need is:
1. service x sends message to y
2. y on receiving message sends another message to z

Thank you!

**Comment by nockstarr** [comment]
You can basically use my example over, but get rid of the connection pooling if you don't need it as @mosquito suggested.
You may need to update the code a bit for the latest and greatest aio-pika as my example is 3 years old.

**Comment by durgeksh** [comment]
Hi
Could you please share the whole code?
Thank you!
