### ISSUE TITLE
incorrect type annotation on add_close_callback's callback parameter

### ISSUE THREAD

**Issue by brianmaissy** [mosquito/aio-pika#289]
The signature of `Connection.add_close_callback` is currently as follows:

`def add_close_callback(self, callback: Callable[[], None]):`

According to the docstring, the `callback` will be passed an `asyncio.Future` as the first argument. The current signature implies that it will be called with no arguments.

I think the correct annotation is:
`def add_close_callback(self, callback: Callable[[asyncio.Future], None]):`
or if you would rather not specify the arguments:
`def add_close_callback(self, callback: Callable[[...], None]):`

Happy to open a PR if this sounds ok.

**Comment by brianmaissy** [comment]
Although now that I take a closer look, it looks like the docstring might also be incorrect, and the argument to the callback is an `Exception`, not a `Future`?

**Comment by mosquito** [comment]
good find. Yeah, let's fix it.

**Comment by brianmaissy** [comment]
@mosquito did you get a chance to look at my PR?
