### ISSUE TITLE
crash when delivery mode not specified in message

### ISSUE THREAD

**Issue by dmacnet** [mosquito/aio-pika#3]
I started testing compatibility between this module and the asynqp Python AMQP module. aio-pika crashes with a TypeError when reading a message that doesn't specify delivery mode, in message.py line 39:
`self.delivery_mode = DeliveryMode(int(delivery_mode)).value`
It fails to convert NoneType to an int.
I am not positive whether the delivery mode field of a message is required, but it would be nice to have either cleaner reporting of the problem or defaulting of the value in aio-pika, to check whether it is None before trying to convert it to an int.

**Comment by mosquito** [comment]
What you want to see by default when "None" was passed?

**Comment by mosquito** [comment]
I think It's must be explicit and required.

**Comment by dmacnet** [comment]
OK, in that case I think I'd prefer that it log and discard malformed messages rather than raise an exception. Do you have a consistent approach to handling messages that are malformed in other ways?
I've opened an issue with asynqp about creating messages that lack that field, to hopefully deal with it on their end also.

**Comment by ollamh** [comment]
@mosquito I've got the same issue when using django channels as the message sender. And I see in the official pika spec that delivery_mode can be None (pika.spec.BasicProperties https://github.com/pika/pika/blob/master/pika/spec.py#L2074). 
But aside from that fact, I see that current Message class implementation assumes non-persistency for all incoming messages without delivery_mode explicitly being set. I believe the same behavior may be kept by moving default value initialization inside class initialization thus accepting None values. What do you think?

**Comment by mosquito** [comment]
What default value I should be set?

**Comment by ollamh** [comment]
I see you already set it to non-persistent which for me is fine

**Comment by mosquito** [comment]
Ok. 😊

**Comment by ollamh** [comment]
Great! Thank you! I can make PR if it speed up the things =)

**Comment by mosquito** [comment]
@ollamh, feel free to create PR.

**Comment by mosquito** [comment]
Fixed in [0.9.4](https://pypi.python.org/pypi/aio-pika/0.9.4)
