### ISSUE TITLE
Submit payments to maintainers of the Python ecosystem

### ISSUE THREAD

**Issue by pydanny** [mosquito/aio-pika#30]
Since you insist on using bleeding edge components in production, and feel you have the right to harass maintainers when those bleeding edge components have problems, you should be paying the maintainers for their unpaid volunteer time. Contact maintainers to request their Patreon accounts (or other similar services) and send them at least 4 hours of their hourly rate per month.

Reference: https://github.com/pypa/setuptools/pull/1043

**Comment by mosquito** [comment]
That's not a valid issue for this repository. But actually I can pay my time. I invest a lot of free time in open source projects (such as this one).

**Comment by pydanny** [comment]
If you invest your time in open source projects, then why are you harassing other maintainers? Don't you get it: we're all in this together.

**Comment by mosquito** [comment]
I apologize if I offended someone. However, I wrote only the facts. The ecosystem was actually broken. The worst thing is that there was no way to get around this problem for me. @jaraco did everything right after all. Everyone could make such a mistake.
