### ISSUE TITLE
message.reject called inside ProcessContext.__exit__ fails when channel is closed

### ISSUE THREAD

**Issue by DXist** [mosquito/aio-pika#302]
I'm using ProcessContext in my consumer implementation and get error:

```
AttributeError
'NoneType' object has no attribute 'write'
```
in https://github.com/mosquito/aiormq/blob/bedf52cee682777435c71486e1614636aedc9330/aiormq/channel.py#L411

This exception is raised during handling of [ChannelInvalidStateError](https://github.com/mosquito/aiormq/blob/bedf52cee682777435c71486e1614636aedc9330/aiormq/channel.py#L89) raised inside the body of ProcessContext context manager.

ProcessContext tries to [reject](
https://github.com/mosquito/aio-pika/blob/3915d2fd8e9c377197b5613bd4f5aeb6035a2826/aio_pika/message.py#L673) the message but fails to do that because the channel is closed.

**Comment by DXist** [comment]
In my code I handle `aio_pika.exceptions.DeliveryError` to nack consumed messages and use the same channel for consumer and publisher. I could handle `ChannelInvalidStateError` in client code on publish and decide whether to send nacks for consumed message or not. Or handle DeliveryError on publish and try do send nack for consumed message and ignore `ChannelInvalidStateError` that would happen on closed channel.

I like the first approach more.

**Comment by mosquito** [comment]
Maybe you could provide a PR?

**Comment by DXist** [comment]
@mosquito [here](https://github.com/mosquito/aio-pika/pull/306) you go
