### ISSUE TITLE
Queue.iterator() can "block" event loop

### ISSUE THREAD

**Issue by wyfo** [mosquito/aio-pika#315]
~~`aoi_pika.Queue.iterator()` uses a hidden `asyncio.Queue` to temporary store message. Even if it seems to be just an implementation detail, there is a side effect that it is worth to know and maybe to explicit in the documentation : `asyncio.Queue.get` is synchronous when the queue is not empty.
In the case of a queue receiving messages faster than it consumes them, the `asyncio.queue` is never empty and there is no event loop context switch with iterations. Moreover, if the handling of the message is synchronous too, there is no context switch at all; the loop is actually "blocked" in an infinite loop.
(In my case, the signal handler added with `loop.add_signal_handler` could even not execute to shutdown gracefully my application)~~

~~I know that there is no obligation for  an asynchronous iterator to make a context switch, and a lot of them doesn't, but the issue there is about the potential infinite loop because the (potentially synchronous) iterator is potentially infinite.
I see two solution to this issue :~~
- ~~adds a context switch (`asyncio.sleep(0)`) in each iteration, or only if the queue is not empty; it radically prevents this issue, with a small cost~~
- ~~put a warning in the documentation about the fact that the iteration is synchronous when the queue is not empty and that could lead to infinite loop if the rest of the code is synchronous too~~
- ~~do nothing (of course an other possible solution)~~

EDIT I was wrong and wrote my issue too quickly. (if the loop was blocked, no other messages could be added to queue) Sorry.

**Comment by mosquito** [comment]
You're welcome.
