### ISSUE TITLE
ACK is not awaitable

### ISSUE THREAD

**Issue by gilbsgilbs** [mosquito/aio-pika#32]
Hi there,

Looking at [this section of the documentation](https://aio-pika.readthedocs.io/en/latest/rabbitmq-tutorial/2-work-queues.html#message-acknowledgment), `message.ack()` is not awaited, which means that the ack will be blocking. Do you hope that it won't block long enough to be significant? What if RabbitMQ timeouts? Is that due to some implementation difficulty? (AFAICS, neither can Twisted consumer await the ack).

Thanks.

**Comment by mosquito** [comment]
Please see the #7

**Comment by gilbsgilbs** [comment]
Great! Thanks for this fast answer. I knew I already read that somewhere :) . It should definitely be written somewhere in the FAQ.

Is this behavior introduced by `aio-pika` or by `pika` itself? I can't see anything related to a “non-blocking socket” in `aio-pika`, but I'm unsure where I should look.
