### ISSUE TITLE
Any example on consuming with cpu-intensive long running tasks 

### ISSUE THREAD

**Issue by clippered** [mosquito/aio-pika#342]
Hi,

I just want to check if there are any examples out there for consuming messages then processing them in a couple of minutes in a CPU intensive process before sending back the ack. When this is performed inside the consume callback, looks like the connection is dropped and the message is redelivered.
Is it a good idea to put this in a thread instead, then signal back to the callback to do the ack when the thread finishes?
Thanks.

**Comment by dizballanze** [comment]
Hi,

CPU intensive process may block event loop and aio-pika won't send heartbeats.
Try to use separate thread/process for CPU intensive tasks.

**Comment by clippered** [comment]
thanks for the answer, let me try this first in the next days and see if it works. Its just that I think the CPU intensive thread might not give way for aio-pika to send heartbeat.

**Comment by dizballanze** [comment]
> Its just that I think the CPU intensive thread might not give way for aio-pika to send heartbeat.

That shouldn't happen. OS will switch threads from time to time.

**Comment by clippered** [comment]
Thanks @dizballanze , I thought that Python's GIL is also not giving way for other thread, I may have misunderstood it. I'll close this one then.

**Comment by clippered** [comment]
@dizballanze I know this is closed but unfortunately, even if the worker is in a new thread of its own, it is running in 100% CPU utilisation for about 2 minutes and the RabbitMQ broker has missing heartbeats after 1minute. Looks like the OS (Linux) did not switch threads in this case.

**Comment by mosquito** [comment]
You shouldn't start worker in separate thread. You should call each blocking function to the separate thread. The simple way is  wraps [@threaded](https://pypi.org/project/aiomisc/#id23) decorator  around blocking function.

**Comment by nidu** [comment]
Is there any way to specify a heartbeat like here (https://pika.readthedocs.io/en/stable/examples/heartbeat_and_blocked_timeouts.html)?
I have a single sync long running function to call and it doesn't play nicely with aio-pika so far unfortunately.

**Comment by durgeksh** [comment]
Hi,
I want to consume a message and start a new process on which long task will be run. At a same time, only one message should be consumed and task associated with it should be completed. As it is stated, it reschedules the message even though it is being processed. I am using separate process so that after completion of long task, RAM should be reclaimed by OS. 

`import asyncio
import multiprocessing
import time
from aio_pika import connect
from aio_pika.abc import AbstractIncomingMessage

def process_function(message):
    print(message)
    time.sleep(180)
async def on_message(message: AbstractIncomingMessage) -> None:
    async with message.process():
        p1 = multiprocessing.Process(target=process_function, args=(message.body, ))
        p1.start()
        p1.join()        

async def main() -> None:
    connection = await connect("amqp://guest:guest@localhost/")
    async with connection:
        channel = await connection.channel()
        await channel.set_qos(prefetch_count=1)
        queue = await channel.get_queue("hello")
        await queue.consume(on_message)
        await asyncio.Future()


if __name__ == "__main__":
    asyncio.run(main())`

Thank you and could you please correct me what's wrong with above code that it reschedules the same message again and processes same repeatedly.
Thank you!

**Comment by tsdaemon** [comment]
@durgeksh I was trying the same problem with multiprocessing, and I found out what was wrong with your code. It works if do following:
```
p1.start()
while True:
    not p1.join(timeout=10)
    if not p1.is_alive():
        break
    await asyncio.sleep(1)
```
So a simple p1.join() blocks the execution and asyncio, effectively enforcing the same problem we are trying to solve – release the execution loop for asyncio to switch context and send a heartbeat. `p1.join(timeout=10)` with a timeout unblocks every 10 seconds, and await asyncio.sleep(1) allows to switch threads.

In our case we eventually solved this problem by running tasks in a separate thread, but it also will work with a separate process.

**Comment by durgeksh** [comment]
Thank you.

**Comment by abhi12299** [comment]
If your message process function is async, here's what you can do:
```python
async with queue.iterator() as queue_iter:
    async for message in queue_iter:
        async with message.process():
            try:
                # Create a task for message processing
                process_task = asyncio.create_task(process_message(message))
                # Wait for the task with periodic checks
                while not process_task.done():
                    try:
                        await asyncio.wait_for(asyncio.shield(process_task),timeout=5.0)
                    except asyncio.TimeoutError:
                        # This is expected, just continue waiting
                        continue
                    except Exception as e:
                        # Re-raise other exceptions
                        raise e

                # Get the result (and propagate any exceptions)
                await process_task
```
