### ISSUE TITLE
`basic_cancel` is not implemented

### ISSUE THREAD

**Issue by gilbsgilbs** [mosquito/aio-pika#35]
Hi there,

As far as I can see in the code and in the documentation, [`basic_cancel`](https://github.com/pika/pika/blob/51fd186f1fabe0da8582609d266df1e28e57e3f4/pika/channel.py#L202) is not implemented in `aio-pika`. Moreover, it's currently not possible to hack around this, since aio-pika's `consume` method doesn't return the consumer tag.

May I submit a PR for this?

Thanks,
Gilb's

**Comment by mosquito** [comment]
Let's rewiew #36

**Comment by gilbsgilbs** [comment]
Great, thanks :) .

**Comment by mosquito** [comment]
the `0.12.0` already released
