### ISSUE TITLE
Can I make master handle messages sequentially?

### ISSUE THREAD

**Issue by nidu** [mosquito/aio-pika#350]
Hello,

I'm using [master/worker](https://aio-pika.readthedocs.io/en/latest/patterns.html#master-worker) pattern to handle the load, but I noticed that master can take handle multiple messages at the same time, which is not desired in my case.

Is there any way to make master handle message one after another?
Minimal-changes option I see is to close master when message is received and reopen it afterwards, but it sounds suboptimal.

Thanks!

**Comment by mosquito** [comment]
Just use `set_qos` on channel which passed to `Master`

**Comment by nidu** [comment]
Thanks! `await channel.set_qos(1)` did the trick!
