### ISSUE TITLE
UI friendly connection name, connection_name

### ISSUE THREAD

**Issue by honarkhah** [mosquito/aio-pika#360]
There was an [issue](https://github.com/mosquito/aio-pika/issues/264) about it and was developed on the [PR-265](https://github.com/mosquito/aio-pika/pull/265) connection [class](https://github.com/mosquito/aio-pika/blob/524eacbe1eaf5394556c5737473830374406d5e0/aio_pika/connection.py#L310) But if you check the[ latest release connection class ](https://github.com/mosquito/aio-pika/blob/6.7.1/aio_pika/connection.py#L333) you will find it removed! 
Could someone check it!

**Comment by JustinTArthur** [comment]
#265 wasn't enough to fix it. I suspect your issue is a duplicate of #301, which will be fixed by upstream PR mosquito/aiormq#94. I'm not sure when @mosquito will have time to review.

**Comment by honarkhah** [comment]
Yes it is, then I will close this issue, let's continue there.

**Comment by mosquito** [comment]
Sorry for that, I'm still doing a lot of aiormq and aio-pika refactorings in the background and my full-time job is stealing more time than I expected. So there really isn't enough time for public questions.

**Comment by JustinTArthur** [comment]
@mosquito not a problem and I totally understand. I think a lot of open source is in this state right now.
