### ISSUE TITLE
aio-pika became slow if there is a dns resolving process 

### ISSUE THREAD

**Issue by jimmyshe** [mosquito/aio-pika#362]
My rabbit server is configured using zero-config, so I connect to it using url "xxx.local". I noticed there is a huge performance hit when I use  "xxx.local" for connection instead of a real ip.

This is the test scrip for showing the performance hit. 

It is almost 100x slower when I use the local domain.

```
import asyncio
import aio_pika
import datetime


async def main(loop):
    #connection = await aio_pika.connect("amqp://guest:guest@xxx.xxx.xxx.xxx/", loop=loop)
    connection = await aio_pika.connect("amqp://guest:guest@xxx.local/", loop=loop)

    routing_key = "test_queue"
    channel = await connection.channel()
    num_of_messages = 10000
    start = datetime.datetime.now()
    msg = aio_pika.Message(body=b'hello')
    for _ in range(num_of_messages):
        await channel.default_exchange.publish(
            msg,
            routing_key=routing_key
        )
    tt = datetime.datetime.now() - start
    print(tt.total_seconds(), num_of_messages/tt.total_seconds())
    await connection.close()


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
    loop.close()
```

It looks like the publish function is resolving the domain every single time.

This is may not be a bug but I think it is worth for me to point this out.

**Comment by mosquito** [comment]
aio-pika using aiormq which uses [asyncio.open_connection](https://docs.python.org/3/library/asyncio-stream.html#asyncio.open_connection) for made new connection [here](https://github.com/mosquito/aiormq/blob/master/aiormq/connection.py#L228-L230)

**Comment by jimmyshe** [comment]
I see.

**Comment by gonzalesMK** [comment]
Hey, I noticed the same problem... is there a work around for it ?

**Comment by mosquito** [comment]
@gonzalesMK this project uses the library call `asyncio.open_connection` which also performs name resolution. If I'm not mistaken, the `gethostbyname` call is used under the hood in the thread pool, and you are waiting for it before starts the connection. If you have any ideas on how to speed up the standard gethostbyname call for your case, you should write to the 
developers of your OS about it. 

However, it seems to me that in your case, the service responsible for the operation of domain name (or zone) does not respond with the speed that you expect.

You should also check that nsswitch is configured properly if your using Linux.

**Comment by jimmyshe** [comment]
> Hey, I noticed the same problem... is there a work around for it ? 

What I did  is that I performed the name resolving explicitly ahead, and use the ip address afterwards.
