### ISSUE TITLE
Expose message/consumer counts from declare_queue

### ISSUE THREAD

**Issue by connec** [mosquito/aio-pika#37]
Due to the `Queue` abstractions it's currently impossible to safely get the [actual result](https://github.com/pika/pika/blob/0.10.0/pika/spec.py#L1014) of the `queue.declare` operation, along with the `message_count` and `consumer_count`.

A trivial solution would be to add `message_count` and `consumer_count` to `Queue`, and then set it [here](https://github.com/mosquito/aio-pika/blob/master/aio_pika/queue.py#L66) along with `name`. Would this be an acceptable approach for a PR?

**Comment by mosquito** [comment]
Course, do it. Please follow [the rules](https://github.com/mosquito/aio-pika#for-contributors) from `README.md`

**Comment by connec** [comment]
PR opened @mosquito.

**Comment by mosquito** [comment]
Fixed in 0.15.0
