### ISSUE TITLE
Error: "Set size changed during iteration"

### ISSUE THREAD

**Issue by torarvid** [mosquito/aio-pika#388]
We experienced this in production a few times (screenshot from Sentry):

<img width="653" alt="image" src="https://user-images.githubusercontent.com/439758/117623318-e833db00-b173-11eb-8693-64df401d2c5e.png">

My guess is that this is due to the async nature of aio-pika; that while iterating through the set, the await call inside the iteration body causes a possibility for that coroutine to yield, and another to run. If `declare_exchange` is called before the set iteration is complete, I think this could happen...

Edit: Our version of aio-pika is 6.7.1

**Comment by Vasiliy566** [comment]
have same problem

**Comment by mosquito** [comment]
@Vasiliy566 @torarvid in the `aio-pika~=8.0` [it's was fixes](https://github.com/mosquito/aio-pika/blob/8.0.3/aio_pika/robust_channel.py#L88-L89).
