### ISSUE TITLE
basic_nack not implemented

### ISSUE THREAD

**Issue by gilbsgilbs** [mosquito/aio-pika#39]
Hi,

That's not a big issue since we can still use [`reject`](https://aio-pika.readthedocs.io/en/latest/apidoc.html#aio_pika.IncomingMessage.reject) to perform almost the same operation, but although `basic_nack` is mentioned [here](https://aio-pika.readthedocs.io/en/latest/apidoc.html#aio_pika.IncomingMessage) in aio-pika's documentation, I don't see any way to perform a nack using `aio-pika`. Therefore, it's not possible to "reject" multiple messages at once. Moreover, it's semantically a bit different.

Thanks.

**Comment by mosquito** [comment]
@gilbsgilbs can you imagine a code example for this method?

**Comment by gilbsgilbs** [comment]
@mosquito As I understand it, `basic_nack` looks functionnaly very similar to [`basic_ack`](https://aio-pika.readthedocs.io/en/latest/apidoc.html#aio_pika.IncomingMessage.ack), except that you can choose to requeue the message(s) or not. Therefore, I reckon it should just have the same prototype as `basic_ack` with an extra `requeue` parameter that defaults to `False`.

To be honest, I never tested multiple messages (n)acknowledgement using aio_pika.

**Comment by mosquito** [comment]
Implemented in [aio-pika 1.2.0](https://pypi.python.org/pypi/aio-pika/1.2.0)
