### ISSUE TITLE
feature request: RabbitMQ streams support

### ISSUE THREAD

**Issue by eliska-v** [mosquito/aio-pika#402]
RabbitMQ 3.9.0 has introduced [streams](https://blog.rabbitmq.com/posts/2021/07/rabbitmq-streams-overview/). Are there plans to support this feature (and the [binary protocol](https://github.com/rabbitmq/rabbitmq-server/blob/v3.9.x/deps/rabbitmq_stream/docs/PROTOCOL.adoc))?

**Comment by process0** [comment]
I came across this recently. https://github.com/qweeze/rstream

**Comment by Gsantomaggio** [comment]
There are different clients for the custom protocol.

**Comment by mosquito** [comment]
Streams feature available over AMQP, please read related RabbitMQ documentation.
