### ISSUE TITLE
OpenTelemetry tracing

### ISSUE THREAD

**Issue by dokazhi** [mosquito/aio-pika#405]
Add tracing all process_message and other calls for jaeger or smth else

**Comment by decaz** [comment]
The tracing object should be your algorithm, not the internal code of the library.

**Comment by dokazhi** [comment]
https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/fastapi/fastapi.html

I mean somethings like this?

**Comment by decaz** [comment]
This instrumentation extends FastAPI as a separate middleware so it works like a plugin. It makes sense because you don't need to wrap all your API routes by separate decorator for instance. And you should do something like that on your own algorithm.
