### ISSUE TITLE
How do I make aio-pika wait for a long task to complete?

### ISSUE THREAD

**Issue by DefaultPerson** [mosquito/aio-pika#406]
Hello! Привет!
I use the example from the documentation:
producer
```python

async def run_rabbitmq_queue(user_id:int) -> None:
    connection = await connect_robust(f"amqp:///{USER}:{PASS}@127.0.0.1/",)
    async with connection:
        channel = await connection.channel()
        master = Master(channel)
        await master.create_task(
            "my_task_name", kwargs=dict(user_id=user_id))
```
worker
```python
async def main() -> connection.ConnectionType:
    connect = await connect_robust(f"amqp://{USER}:{PASS}@127.0.0.1/")
    channel = await connect.channel()
    await channel.set_qos(prefetch_count=1)
    master = Master(channel)
    await master.create_worker("my_task_name", worker, auto_delete=True)
    return connect
```

If the task is not long, everything works, but when the task is long, I get a message in the log after executing one of the functions:
"Reject is not sent since channel is closed" 
and the task is not finished.

How to solve this problem?

**Comment by bokolob** [comment]
I would recommend  run long tasks in separate thread, look at run_in_executor

**Comment by DefaultPerson** [comment]
> I would recommend run long tasks in separate thread, look at run_in_executor

Thank you so much! It worked!
