### ISSUE TITLE
Disable heartbeat =0 in uri not work

### ISSUE THREAD

**Issue by fortunto2** [mosquito/aio-pika#410]
Hi, i try set ?heartbeat=0 for long tasks

aio-pika 6.8.0
aiormq 3.3.1
rabbitmq RabbitMQ 3.9.5

```python
async def main():
    print('----------------')
    # Perform connection
    connection = await connect_robust(
        "amqp://user:******@xxxxxxx/vhost?heartbeat=0",
        client_properties={
            'connection_name': 'Worker'
        }, timeout=100
    )
    
    print(connection)
    # Creating a channel
    channel = await connection.channel()
    await channel.set_qos(prefetch_count=1)
    print(channel)

    # Declaring queue
    queue = await channel.declare_queue(
        "task_queue",
        durable=True,
        timeout=100
    )
    print(queue)
    print('----------------')

    # Start listening the queue with name 'task_queue'
    await queue.consume(on_message, no_ack=False)

```
but connection created with heartbeat=60s
Why?
Maybe need update aiormq to 4-5?

Same question https://github.com/mosquito/aio-pika/issues/224

**Comment by mimre25** [comment]
I'd also like to have the option to disable the heartbeat with aio-pika.

@mosquito any idea when this will be possible? Is this scheduled?

**Comment by mosquito** [comment]
The [latest version](https://pypi.org/project/aiormq/6.1.1/) has the correct behavior. As you can see when the `heartbeat=0` the `aiormq` sending the correct value.

<img width="1724" alt="Screen Shot 2022-02-09 at 11 51 23" src="https://user-images.githubusercontent.com/792981/153159585-e74242c5-fd12-4e45-b4bf-70707ab941d9.png">

You should upgrade or double-check your broker configuration.

**Comment by mimre25** [comment]
I'm a bit confused.

`aio-pika 6.8.2` requires `aiormq<4,>=3.2.3`. How would I get those two working together?

**Comment by mosquito** [comment]
@mimre25 #436 will fix this

**Comment by mosquito** [comment]
@mimre25 you can help with this, while the reviewers are reviewing changes, you can try the beta version with the command:
`pip install --pre aio-pika`

I am very concerned about the issue of migrating user code from version 6 to version 7. Now it looks like I managed to collect all the migration issues in the (changelog)[https://github.com/mosquito/aio-pika/pull/436/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR1].

You will help us a lot if you try the beta version in your project, and write a report about it.

**Comment by mimre25** [comment]
@mosquito thanks for all the help, it turned out, I didn't even need the setting but rather had to exclude `aio-pika` from being frozen by `freezegun` during my tests

**Comment by mosquito** [comment]
@fortunto2 since version 7.0.0 I can not reproduce this issue.
