### ISSUE TITLE
incorrect work queue.get for single message

### ISSUE THREAD

**Issue by ghost** [mosquito/aio-pika#430]
Dont work timeout in queue.get (https://aio-pika.readthedocs.io/en/latest/quick-start.html?highlight=queue.get#get-single-message-example), run one try of read message and dont try if empty, exit without timeout.

**Comment by Dementiy** [comment]
Is there any progress on this issue?

**Comment by mosquito** [comment]
Timeout for rabbitmq rpc calls is a network communication timeout. Is not a getter timeout. RabbitMQ returns Basic.Empty frame when queue is empty, it's a non blocking calls.
