### ISSUE TITLE
Channel Close callback gets called multiple times in version 6.8.2

### ISSUE THREAD

**Issue by jpieger** [mosquito/aio-pika#437]
This is a regression I found going from version 6.8.1 to 6.8.2.
If a callback is registered on a channel object via `add_close_callback()`, then this callback is triggered once in 6.8.1 and twice in 6.8.2.

Additionally, in 6.8.2 an error log is triggered, even when the channel was closed normally and no error happened. This seems to have the same underlying cause as the double callback.

The following minimal example reproduces the issue:

```python
import aio_pika
connection = await aio_pika.connect_robust("amqp://guest:guest@localhost")
channel = await connection.channel()

channel.add_close_callback(lambda *args: print("Closing", args))

await channel.close()
```

Using aio-pika 6.8.1 it outputs the following:

```
 Closing (<RobustChannel "None#Not initialized channel">, None)
```
And in 6.8.2:

```
Closing (<RobustChannel "None#Not initialized channel">, <Future finished exception=CancelledError()>)
Robust channel <RobustChannel "None#Not initialized channel"> has been closed.
NoneType: None
Closing (<RobustChannel "None#Not initialized channel">, None)
```
The line "Robust channel [...] has been closed" is the error log statement that is additionally triggered. I believe this is because the first time the callback is triggered, it carries an CancelledError exception. However this is not a "real" exception, as there are no type/traceback information attached (as seen from the "NoneType: None" output). Grepping over the code makes me believe, that the exception object originates from [this](https://github.com/mosquito/aio-pika/blob/293569b906a6a4f98eca73d4fb08079ff32d0f97/aio_pika/connection.py#L29) default parameter.

**Comment by raspe88** [comment]
I can verify this issue. Found the same issue.

**Comment by mosquito** [comment]
@jpieger unfortunately, I am currently spending all my free time on the release of the new major version of `aiopika==7.0.0`, if you try to reproduce it on the new version, you will help me a lot.

You can install the beta version with this command: `pip install --pre 'aio-pika~=7.0.0b6'`

**Comment by jpieger** [comment]
I could not reproduce it on version 7.0.0.

Checking the diff between 6.8.1 and 6.8.2, I think it is [this](https://github.com/mosquito/aio-pika/compare/6.8.1...6.8.2#diff-a741c717972435cf80e4f425fe73af7f3597302df570ddd567fac31852e25659R208) line that introduces the bug.

**Comment by mosquito** [comment]
> Checking the diff between 6.8.1 and 6.8.2, I think it is this line that introduces the bug.

Obviously yes, but the problem is not with this change directly. The problem seems to be that in the new version, the channel state is calculated a little differently and it's probably not reproducing.

**Comment by mosquito** [comment]
@jpieger I am endlessly interested in how the migration process to version 7 went. Did I have to change something in your code?

Please write as much as possible about this.

**Comment by jpieger** [comment]
In our codebase we imported `pamqp.specification` in a few places, this module was no longer available in 7.0.0.
I patched the code with a few dirty hacks to avoid the import errors, but that was the only code change necessary.
After that our testsuite ran without errors. I did not explore the topic in more depth, but our testsuite did fail with 6.8.2.

**Comment by mosquito** [comment]
Thank you for your answer, it is very important for me to understand the problems of migration right now.

If there is anything else, please write a comment [here](https://github.com/mosquito/aio-pika/pull/436/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR55).

**Comment by DriverX** [comment]
+1

After upgrade 6.8.1 -> 6.8.2 we have a lot log messages like that with logging.ERROR level

```
Robust channel <RobustChannel "None#Not initialized channel"> has been closed.
NoneType: None
```

I guess `NoneType: None` is traceback exception, but looks strange.

I hope the hotfix is on the way.
