### ISSUE TITLE
New release request 

### ISSUE THREAD

**Issue by eldar-fairfly** [mosquito/aio-pika#45]
The last version was on Feb 13 https://github.com/mosquito/aio-pika/releases/tag/0.6.3 following lots of commits not packed in new version. 
Could @mosquito you please release another version `0.6.4`?

**Comment by mosquito** [comment]
Actually I make releases with setuptools. Full list of packages [here](http://pypi.python.org/simple/aio-pika/)

**Comment by mosquito** [comment]
I start to tags for this repo. If you want to add old versions, please info me.
