### ISSUE TITLE
Is there a option to set acknowledgement-timeout  per channel or connection in RMQ?

### ISSUE THREAD

**Issue by sandeepkumar-one** [mosquito/aio-pika#451]
As specified here(https://www.rabbitmq.com/consumers.html#acknowledgement-timeout) there is a global acknowledgement-timeout for RMQ server. Is there option in aio-pika to set it at channel or connection level.

**Comment by mosquito** [comment]
Thats not a part of communication protocol it's a RabbitMQ server option if I remember correctly.
