### ISSUE TITLE
Misleading Connection.channel example in doc string.

### ISSUE THREAD

**Issue by Marcin-Szadkowski** [mosquito/aio-pika#458]
The example in the following link is wrong. When creating channel working in transactional mode `publisher_confirms` should be set to
`False` instead of `True`.

https://aio-pika.readthedocs.io/en/latest/apidoc.html?highlight=confirms#aio_pika.Connection.channel

![image](https://user-images.githubusercontent.com/55405821/164424071-b9f708e9-2e85-4d90-b22f-e0f71606d690.png)

**Comment by mosquito** [comment]
fixed in #456
