### ISSUE TITLE
Feature request: providing amqp "connection.update_secret" implementation for refreshing tokens 

### ISSUE THREAD

**Issue by deschmih** [mosquito/aio-pika#481]
Hey, 
while connecting to rabbitmq and using jwt in an oauth2 manner, a token refresh before expiring is necessary. Currently I can do this only in the way closing the connection and open again. 
Since AMQP 0.9.1 https://www.rabbitmq.com/amqp-0-9-1-reference.html there is another option to do this. Connection.update-secret is the preferred way to do this. 
Update-secret is implemented in pamqp library. It would be nice to have this feature available in aio-pika.connection as a separate method.

**Comment by mosquito** [comment]
@deschmih feel free to  join the [review](https://github.com/mosquito/aiormq/pull/145).

**Comment by deschmih** [comment]
You have done a good really job. Many Thanks for this. 
But I think you should also bump version in setup.py to aiormq~=6.4.0
https://github.com/mosquito/aio-pika/blob/8c1515127d37df5997d869c5129d119d5f65e12a/setup.py#L41

**Comment by deschmih** [comment]
@mosquito To get a tagged version would be the icing on the cake. ;-)
Many thanks.
