### ISSUE TITLE
How should I implement an asynchronous consumer with timeout

### ISSUE THREAD

**Issue by mastern2k3** [mosquito/aio-pika#488]
I have an architecture where there's an allocation component watching rabbitmq queues and spawning worker processes to digest said queues.

The workers spawn targeted at a specific queue and are expected to consume messages until no more are left, then linger for a period of time before shutting down.

I am currently using a pattern where I simply [get messages one by one](https://aio-pika.readthedocs.io/en/latest/quick-start.html#get-single-message-example) which allows me to check whether there are any new messages waiting and terminate once a certain duration has timed out.

Roughly like this:

```py
    async def _wait_message(self, queue: AbstractQueue, linger: timedelta) -> Optional[AbstractIncomingMessage]:

        timeout = datetime.now() + linger

        while True:

            raw_message = await queue.get(fail=False)
            if raw_message is not None:
                return raw_message

            if datetime.now() >= timeout:
                return None

            await asyncio.sleep(0.5)
``` 

This works well, but, I would like to make this code asynchronous using [the asynchronous api](https://aio-pika.readthedocs.io/en/latest/quick-start.html#asynchronous-message-processing), e.g. :

```py
await queue.consume(self.process_message)
```

The thing is - I can't find a way to make it work the same for the asynchronous api, and would love some help.

**Comment by mosquito** [comment]
Tell me more about your task, it looks like you are trying to misuse rabbitmq correctly in the above problem statement.

**Comment by Lancetnik** [comment]
@mastern2k3 you can create asyncio.Task(cancal_consumer) with delayed with your time  and cancel and recreate this task everytime a message consumed. This way you can prolong consuming stopping, but finally, it will be stopped if there no messages for a long time.

**Comment by mastern2k3** [comment]
@Lancetnik  Super old question but your solution is great!
Exactly what I was looking for!

Sorry @mosquito I guess I missed you're question back then :sweat_smile: ..
