### ISSUE TITLE
SSLContext set on robust_connection

### ISSUE THREAD

**Issue by gonzalesMK** [mosquito/aio-pika#489]
The aiormq Connection accepts the parameter  context: ssl.SSLContext, but I didn't find a way to input this parameter.

I checked that 'context'  should be added to  RobustConnection.KWARGS_TYPES. I can help with this change... but is there another way ? 

I use this parameter to disable hostname check

**Comment by mosquito** [comment]
After merging #474 will be possible.

**Comment by mosquito** [comment]
Resolved in [8.2.0](https://pypi.org/project/aio-pika/8.2.0/)
