### ISSUE TITLE
Add api to get default exchanges

### ISSUE THREAD

**Issue by hellysmile** [mosquito/aio-pika#5]
Creating of Exchange is very hard due https://github.com/mosquito/aio-pika/blob/master/aio_pika/channel.py#L99
So there is now way to use default exchange `''`, cuz it is impossible to declare default exchange

**Comment by mosquito** [comment]
Now available in 0.6.1+

```python

await channel.default_exchnage.publish(
    Message(bytes('Hello', 'utf-8')),
    'my_routing_key'
)
