### ISSUE TITLE
Add connection blocking event handling

### ISSUE THREAD

**Issue by teplinsky-maxim** [mosquito/aio-pika#506]
Hello! Are there any variants to handle connection blocking by rmq server? I have events such as 
```
Connection <Connection: "amqp://guest:******@127.0.0.1:5672/vhost" at 0x7f2551f1c540> was blocked by: 'low on memory'
Connection <Connection: "amqp://guest:******@127.0.0.1:5672/vhost" at 0x7f2551f1c540> was unblocked
```
and I want to stop waiting on connection until the connection is unblocked, is it possible to add an event handler such as [Java has](https://www.rabbitmq.com/connection-blocked.html)? Or maybe I can add handler to this event myself somehow like override Connection class? I know, that the logging code belongs to aiormq/connection.py, but I find it more related to this repo.

**Comment by mosquito** [comment]
The server sends the blocking-related frame and all frames to send to the broker pauses until the unblock-related frame is received (see [this PR](https://github.com/mosquito/aiormq/pull/145/files#diff-0b274c02d15032b07b80f1c5bb42a7ff1972fcd21c487eabdef5df99168f7dd6)).

**Comment by teplinsky-maxim** [comment]
I have a high-loaded services, which can overload the broker. In that case I want to discard unnecessary data to be sent over rmq. Imagine this pseudocode:
```
if connection.is_blocked:
    calculate_info_locally_but_slow()
else:
    send_data_over_rmq_to_calculate_fast()
```

For now I came to creating a class `BlockingDiscardConnection(Connection) # Connection is from aiormq`, but not sure is this a rigth class to inherit from, because I also want the connection to be robust, so I should probably include `RobustConnection` too

**Comment by teplinsky-maxim** [comment]
Yep, it is exactly what I was looking for! 

> 
> ```
> try:
>     await asyncio.wait_for(connection.transport.ready(), timeout=5)
>     send_data_over_rmq_to_calculate_fast()    
> except asyncio.TimeoutError:
>     calculate_info_locally_but_slow()
> ```


Thanks!
