### ISSUE TITLE
Tag/changelog/release for 8.3.0 missing

### ISSUE THREAD

**Issue by torarvid** [mosquito/aio-pika#513]
Hi there 👋🏻 Just got a PR from dependabot about upgrading to v8.3.0. However, I can't see any release notes, tag or github release about it, so a bigger-hurdle-than-normal to see what's changed 🙂

**Comment by mosquito** [comment]
It's my bad, the release was made in a hurry before the new year holidays, and I forgot to do a git push. Now everything is in place.
