### ISSUE TITLE
How to handle ConnectionClose in consume scope?

### ISSUE THREAD

**Issue by eldardamari** [mosquito/aio-pika#54]
Hi @mosquito,

I have a consumer for a specific queue (let's call the queue: `queue_a`).
In `queue_a.consume(consume_callback)`,I'm ack/reject messages manually.
```python
async def consume_callback(message: IncomingMessage):
   try:
        # do stuff
        # message.ack
   except:
        message.reject()
```
while calling `message.reject()` I get sometime ```pika.exceptions.ConnectionClosed``` exception which I find difficult  to refresh!

Any suggestion how to refresh the connection from within `consume_callback`?

**Comment by mosquito** [comment]
`ConnectionClosed` might be raised when `message.ack` or `message.reject` when connection already closed from remote side.

If you want to handle this situation you should call `Channel.add_close_callback` and `Connection.add_close_callback` for set your-own handlers.

But I guess you should to fix your network connectivity or fix your keepalive settings.

**Comment by eldardamari** [comment]
thanks, will check it!

**Comment by mosquito** [comment]
I already started work for implement transparent auto-reconnects. But now I have no enough time for continue this.

**Comment by mosquito** [comment]
I can reproduce it. Looks like the pika-0.12 has some issue with consuming

**Comment by eldardamari** [comment]
nice catch, I'd like to see some references..
what do you think we should do? is pika-0.11 version more stable? 
maybe you should consider to downgrade the pika version.

**Comment by mosquito** [comment]
I'll revert it. Please wait.

**Comment by eldardamari** [comment]
Cool - thanks! 🙏🏻

**Comment by mosquito** [comment]
Please notify me after double check. 😉

**Comment by eldardamari** [comment]
sure, np :)

**Comment by lukebakken** [comment]
@mosquito -

> I can reproduce it. Looks like the pika-0.12 has some issue with consuming

Could you provide the code you used to reproduce?

**Comment by decaz** [comment]
@mosquito let's figure this whole mess out once and for all! Attach the code, please 😃
