### ISSUE TITLE
Feedback required

### ISSUE THREAD

**Issue by Lancetnik** [mosquito/aio-pika#557]
I really like your project and have built many services based on it over the past years. And the general code of these services gradually acquired the form of a completed project - [**Propan**](https://github.com/Lancetnik/Propan).

It is in no way trying to occupy the **aio-pika** place, on the contrary, strongly emphasizes the fact that it is built on its basis. However, perhaps Propan is a high-level solution that will popularize Messaging due to its ease of use.

So I would like to ask: is it possible to add a link to my project somewhere in the  **aio-pika** documentation? In any case, I will be glad to receive any feedback from you @mosquito.

P.S. thanks for your speeches and lections too.

**Comment by mosquito** [comment]
@Lancetnik I thought about adding `see also`-like section to the `README.md` but not collect anought content for it.

Of course you can propose it as a PR, fell free.

So about the `Propan`, looks good anought on the first look, not shure about trying it on my sandbox, or a real project, little bit busy right now.

**Comment by Lancetnik** [comment]
Thanks, I will be back with a PR soon! Is the **Propan** mention should be anouth for **See also** section or needs to add more projects?

**Comment by mosquito** [comment]
If you will be so kind to find something else…

**Comment by Lancetnik** [comment]
It can be a hard job, I suppose
Native `pika` has a some kind of asyncronous connections, but it is too hard integrates with them
Kombu, Nameko, Minos has an AMQP supporting too, but they are still sync...

**Comment by Lancetnik** [comment]
@mosquito appreciate your trust! Now I will worker harder to make a great project
