### ISSUE TITLE
await queue.get() seems to gets stuck when the queue is empty (not getting new elements)

### ISSUE THREAD

**Issue by jakubczaplicki** [mosquito/aio-pika#56]
What should be the correct behaviour in the following case :

```
async def consumer(queue_in):
    while True:
        msg = await queue_in.get()
        await do_stuff(msg)
```

From what I observe is that the queue just gets stuck waiting for an element. But when an element is added to the queue, the `get()` doesn't "see" it, and keeps waiting: `2017-09-07 15:13:50,959 aio_pika.queue  DEBUG    Awaiting message from queue: <Queue(queue_in): auto_delete=False, durable=None, exclusive=False, arguments=None>`

However after adding the timeout:

```
async def consumer(queue_in):
    while True:
        try:
            msg = await queue_in.get(timeout=3.0)
            await do_stuff(msg)
        except TimeoutError:
            await asyncio.sleep(1.5)
```

The `get()` times out (even when an element is added to the queue within the timeout), and in the next iteration it reads all the elements from the queue added in the meantime.

Am I doing something wrong ?

**Comment by mosquito** [comment]
Hello. Please try to reproduce it on `0.21.0` this might be because #54

**Comment by jakubczaplicki** [comment]
I am afraid it still doesn't work with `0.21.0`

This is the script I use to reproduce the issue:  https://gist.github.com/jakubczaplicki/8993755aa70a73c506c07a05c6f65da1 (make sure to change <user>, <pswd>, etc.)

Running `python aio_pika_get_test.py consume` , the script uses queue.consume method and works as expected:
```
Using queue.consume
DEBUG:aio_pika.queue:Start to consuming queue: <Queue(queue_in): auto_delete=False, durable=None, exclusive=False, arguments=None>
DEBUG:pika.channel:Adding in on_synchronous_complete callback
DEBUG:pika.channel:Adding passed in callback
Publish b'Hello World: 0'
DEBUG:pika.channel:0 blocked frames
DEBUG:pika.channel:Discarding frame <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.ConsumeOk(['consumer_tag=ctag1.dce63efa1ef94722a1119231edade9f7'])>"])>
Received (consume callback): b'Hello World: 0'
Publish b'Hello World: 1'
Received (consume callback): b'Hello World: 1'
Publish b'Hello World: 2'
Received (consume callback): b'Hello World: 2'
Publish b'Hello World: 3'
Received (consume callback): b'Hello World: 3'
Publish b'Hello World: 4'
Received (consume callback): b'Hello World: 4'
done
```

running `python aio_pika_get_test.py get`, the script uses queue.get (no timeout by default). Messages are not received : 

```
Using queue.get
DEBUG:aio_pika.queue:Awaiting message from queue: <Queue(queue_in): auto_delete=False, durable=None, exclusive=False, arguments=None>
Publish b'Hello World: 0'
DEBUG:pika.channel:Received Basic.GetEmpty: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.GetEmpty(['cluster_id='])>"])>
Publish b'Hello World: 1'
Publish b'Hello World: 2'
Publish b'Hello World: 3'
Publish b'Hello World: 4'
done
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<consumer_get() done, defined at aio_pika_get_test.py:45> wait_for=<Future pending cb=[FutureStore._on_future_done(), <4 more>, Task._wakeup()]>>
```

```
(venv) [vagrant@localhost test]$ pip freeze | sort
aiohttp==2.2.5
aio-pika==0.21.0
asynctest==0.10.0
async-timeout==1.3.0
chardet==3.0.4
conradlib-aiostreamscrobbler==0.5.0
idea-test-testcase==0.5.1
multidict==3.1.3
parameterizabletests==0.5.1
pika==0.10.0
shortuuid==0.5.0
yarl==0.12.0
```

**Comment by jakubczaplicki** [comment]
Looks like `queue.get` doesn't like empty queue.

Still using the test script: https://gist.github.com/jakubczaplicki/8993755aa70a73c506c07a05c6f65da1

If we publish a message to the queue BEFORE running `queue.get`, `get` will read the first message. It will then read the second message which will be added in the meantime. However but because of a delay between sending messages, next iteration will hit empty queue and will get stuck: 

```
Using queue.get
DEBUG:aio_pika.queue:Awaiting message from queue: <Queue(queue_in): auto_delete=False, durable=None, exclusive=False, arguments=None>
Publish b'Hello World: 0'
Received (get): b'Hello World: -1'
DEBUG:aio_pika.queue:Awaiting message from queue: <Queue(queue_in): auto_delete=False, durable=None, exclusive=False, arguments=None>
Received (get): b'Hello World: 0'
DEBUG:aio_pika.queue:Awaiting message from queue: <Queue(queue_in): auto_delete=False, durable=None, exclusive=False, arguments=None>
DEBUG:pika.channel:Received Basic.GetEmpty: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.GetEmpty(['cluster_id='])>"])>
Publish b'Hello World: 1'
Publish b'Hello World: 2'
Publish b'Hello World: 3'
Publish b'Hello World: 4'

```

**Comment by jakubczaplicki** [comment]
Retested on `1.0.1`  with `robust_connection`.  
`await queue.consume` behaves as expected.
`await queue.get` shows the same issue as previously described.

**Comment by mosquito** [comment]
@jakubczaplicki thank you for your activity. I'll check it as soon as I can.

**Comment by jakubczaplicki** [comment]
No worries. I'll try to be more productive and I'll prepare a PR with a pytest for what we discuss here.

**Comment by mosquito** [comment]
`basic_get` in the pika will return nothing when target queue is empty.

**Comment by mosquito** [comment]
I already added changes and the tests for this behaviour in [aio-pika 1.1.1](https://pypi.python.org/pypi/aio-pika/1.1.1).
