### ISSUE TITLE
Issues with HA RabbitMQ cluster

### ISSUE THREAD

**Issue by awoimbee** [mosquito/aio-pika#567]
Hi,
I tried making a detailed issue but I don't know my way around aio-pika and aiormq enough, so I'll make it simple.

**setup**
I run rabbitmq in a cluster and I use quorum queues. One rabbit instance might become unavailable at any time.
I expect `RobustConnection` to handle reconnects to any rabbit replicas automagically (I'm setup like the example `Asynchronous message processing`).

Seems like aiormq keeps a persistent connection open with a single rabbit replica. When this replica goes down I get these **issues**:
1. An exception is created each time, sending many false alerts my way 
    https://github.com/mosquito/aiormq/blob/f04f0cf7f1972e14abd4fefc90218770f335e239/aiormq/connection.py#L558
2. Occasional `Task was destroyed but it is pending!` (#432) seem to happen when reading a message during rmq shutdown (it happens before `Unexpected connection close` is printed).
    ```
    Task was destroyed but it is pending!
    task: <Task pending name='Task-31' coro=<Connection._on_reader_done.<locals>.close_writer_task() running at /usr/local/lib/python3.10/site-packages/aiormq/connection.py:506> wait_for=<Future finished result=None>>
    task: <Task pending name='Task-38' coro=<OneShotCallback.__task_inner() running at /usr/local/lib/python3.10/site-packages/aio_pika/tools.py:230>>
    ```
3. Occasional `DeliveryError` from `exchange.publish(message, MY_ROUTING_KEY)`, seems to happen in tandem with `Task was destroyed but it is pending!` (before `Unexpected connection close`).

---

Is there a magic bullet to solve all of this ?
Otherwise, how can I help solve these issues ?

**Comment by mosquito** [comment]
@awoimbee if I guess correctly your HA cluater topology and connection endpoint is a DNS records with same name then [this article](https://github.com/mosquito/aio-pika/pull/569/files#diff-4eec6cec5f6fab1548b85433ea8ca81315ae165db4b7f84019f287df9015699fR67-R95) is a possible solution for you.

**Comment by awoimbee** [comment]
Hi, everything is inside a kubernetes cluster, I have a service (a DNS record) that points to rabbitmq pods. The rabbitmq containers are shutdown gracefully.
I don't think happy_eyeballs will help, my issue is not with the reconnect but with the disconnects.
