### ISSUE TITLE
Tutorial 1 missing `channel` assignment

### ISSUE THREAD

**Issue by e-kondr01** [mosquito/aio-pika#596]
https://aio-pika.readthedocs.io/en/latest/rabbitmq-tutorial/1-introduction.html#sending

The following line is missing compared to the official tutorial:

```python
channel = await connection.channel()
```

**Comment by Alviner** [comment]
> https://aio-pika.readthedocs.io/en/latest/rabbitmq-tutorial/1-introduction.html#sending
> 
> The following line is missing compared to the official tutorial:
> 
> ```python
> channel = await connection.channel()
> ```

thanks, feel free to make a pr

**Comment by e-kondr01** [comment]
Took me a while to get to it, but here it is:

https://github.com/mosquito/aio-pika/pull/613
