### ISSUE TITLE
python 3.12 compatibility

### ISSUE THREAD

**Issue by Loki-Afro** [mosquito/aio-pika#602]
hey it looks like that aio-pika is not compatible with python 3.12 and i haven't found an issue yet.

i think it is the same as described here https://github.com/aio-libs/aiohttp/issues/7739

**Comment by mosquito** [comment]
@Loki-Afro I tried making a pipline for 3.12 but in one of the tests something goes wrong, maybe it's a bug or maybe it's just a test problem. I don't have time to figure it out right now. But I think 3.12 should work as it should, it just takes some effort to get it fully compliant.

**Comment by mdczaplicki** [comment]
3.12 doesn't work for me. I'm unable to create a channel from an active connection with RabbitMQ.  
The channel says `Not initialized channel` and there is a traceback visible in PyCharm debugger, but I cannot get the whole output (probably a PyCharm bug).

![image](https://github.com/mosquito/aio-pika/assets/9108586/45b8cef4-9a2e-42d2-8d1c-27ac9b977b72)
