### ISSUE TITLE
Compatibility with TLSv1.3

### ISSUE THREAD

**Issue by gianlucadecola** [mosquito/aio-pika#621]
Hi, I am using aio-pika in a project and for security requirements I'll need to have TLS enabled. In particular I'll need to work with TLSv1.3 but searching in the documentation (also in `aiormq`) I cannot find if this TLS version is specifically supported. 
Can I get some hint on that?

Thanks guys :+1:

**Comment by mosquito** [comment]
This is not a library choice, but a context configured in the user code ssl.

**Comment by gianlucadecola** [comment]
Oh good to know, thank you!
