### ISSUE TITLE
Trying to reconnect after close was invoked

### ISSUE THREAD

**Issue by decaz** [mosquito/aio-pika#63]
Maybe we can save handler at: https://github.com/mosquito/aio-pika/blob/1a70b3d4aa7b6e7ed7a310ce88883ba2e5d47649/aio_pika/robust_connection.py#L77-L80 and then cancel it within the close method, but I think there will be deadlock as it cannot return connection.

**Comment by mosquito** [comment]
Would you like try it?

**Comment by decaz** [comment]
OK, I'll create PR as soon as possible :)

**Comment by mosquito** [comment]
@decaz very well thanks.

**Comment by decaz** [comment]
@mosquito not yet.

**Comment by mosquito** [comment]
@decaz, I still hope you'll finish the PR which close this issue. I closing this issue and I still awaiting.
