### ISSUE TITLE
Client does not seem to be sending heartbeats to RabbitMQ

### ISSUE THREAD

**Issue by dstibrany** [mosquito/aio-pika#64]
I'm trying to configure worker -> rabbitmq using aio-pika and I'd like to keep a long lived connection open, but I'm running in to disconnection issues if there is a lull in activity. I'm noticing that if I set `heartbeat_interval`, this will change how long rabbitmq waits to determine if a connection is 'dead', but has no affect on the interval in which the client sends heartbeats out. In fact, I'm not actually seeing any heartbeats being sent out from the aio-pika client in tcpdump.

Is this a bug in aio-pika or in pika?

**Comment by mosquito** [comment]
I run wireshark and run one of example from sources. After some time I have got heartbeat packet. 
Can you prepare some reproduction scenario?

**Comment by dstibrany** [comment]
Yep, I'll try to reproduce.

**Comment by mosquito** [comment]
Please reopen this issue when this reproduces.

**Comment by a37h** [comment]
@mosquito is it necessary in aio-pika to explicitly send heartbeats somehow? I'm currently using pika and it seems to be important to send them, otherwise the connection drops :c

**Comment by mosquito** [comment]
@a37h it's replying on the server hearbeats and send heartbeat frames when no one frames was sent until heatbeat timeout.

**Comment by wangjianweiwei** [comment]
@a37h  hello
Have you solved your problem? 
I seem to have the same problem as you. 
Consumers will not disconnect the link and the publisher will not be able to use it after a period of time. From Rabbit MQ Management, publishers and consumers are different. Publishers do not have heartbeat data. Consumers will have data at a certain interval, and support automatic reconnection. 
Do publishers re-establish connections every time?

**Comment by viniciusao** [comment]
@dstibrany I face the same thing and by looking at the aio-pika logs is clear that is not sending any heartbeat. A workaround is to use connect_robust with heartbeats disabled.

**Comment by marsonya** [comment]
> eartbeat=65535

Increasing the heartbeat duration is unconventional.
But it works!!

[Checkout](https://www.rabbitmq.com/uri-query-parameters.html) the RabbitMQ url params to see how to use heartbeat.
