### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by awoimbee** [mosquito/aio-pika#649]
Using `aio-pika 9.5.0`
Summed up in one image:

![Screenshot From 2024-11-22 11-52-48](https://github.com/user-attachments/assets/4cc02cdd-5c7c-4f54-bc19-670c86bb7336)

Bug introduced by #615 in v9.5.0

**Comment by zware** [comment]
Fixed by 36cdae8.
