### ISSUE TITLE
API reference page is empty on readthedocs.io

### ISSUE THREAD

**Issue by eebirke** [mosquito/aio-pika#651]
Hi, I noticed that the API reference page is currently empty on `latest`, `stable` and `9.5.0` on https://aio-pika.readthedocs.io/en/latest/apidoc.html

It works again when selecting version 9.4.3.

**Comment by grigory-bogush** [comment]
+ please fix

**Comment by mosquito** [comment]
https://docs.aio-pika.com/ documentation now here

**Comment by eebirke** [comment]
@mosquito Ah, alright. Seems the README still points to the old location in two of the links at the top, btw.

**Comment by mosquito** [comment]
nothing unusual, I had been registered domain and upload docs 2 hours ago )))
