### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by gilbsgilbs** [mosquito/aio-pika#69]
Hi!
Would it be possible to provide a changelog between releases? It's quite hard to figure out what changed or even if there are breaking changes. Therefore, I'm not confident for updating aio-pika in production.

**Comment by gilbsgilbs** [comment]
Great. That was exactly what I was looking for. This should be documented anywhere 😊. Thanks!

**Comment by mosquito** [comment]
https://aio-pika.readthedocs.io/en/latest/#versioning

**Comment by mosquito** [comment]
Since yesterday. 😂

**Comment by gilbsgilbs** [comment]
Just in time ;) . Still, a CHANGELOG file is sometimes useful for services like [sibbell.com](https://sibbell.com). And also to easily understand what changed between two releases when commits were not squashed properly or when commit messages are not that explicit. But I'll stick to the old strategy for now :) .
