### ISSUE TITLE
Error in Channel._channel_maker ?

### ISSUE THREAD

**Issue by fortiema** [mosquito/aio-pika#70]
First of all, thanks for making this library available - Having robust asynchronous AMQP clients is something exciting.

I may be wrong (I'm very new to asyncio so this is all a bit confusing to me still), but there seem to be an error in `_channel_maker` function at [channel.py#L68](https://github.com/fortiema/aio-pika/blob/44127dd87ad15a2cc27cdb2870d868aa0bb0bbc9/aio_pika/channel.py#L68)

```python
def _channel_maker(self):
        return self._connection._connection.channel
```

The first `_connection` refers to `AsyncioConnection`, but it does not have a `_connection` property itself. This means every time the connection is closed, and then re-established, I get this error thrown out:

```
Traceback (most recent call last):
 [...]
    return self._connection._connection.channel
AttributeError: 'NoneType' object has no attribute 'channel'
```

Editing the code to remove the second `_connection` seems to fix the issue for me.

Details:
* python 3.6.2
* aio-pika 1.4.2

**Comment by mosquito** [comment]
It's not a typo. The `aio_pika.Channel` use the `pika.Channel` through `pika.Connection` instance. When connection closes the `pika.Connection` instance is not created yet and this exception raises. 

This behaviour explicit. What behaviour will be fine for you?

**Comment by fortiema** [comment]
Thanks. Not sure I understand - I was under the impression that the error gets thrown at re-connection, where `RobustChannel` tries to re-init itself. It means that the `connection` object passed to `on_reconnect()` has not been instantiated, correct?

```python
def on_reconnect(self, connection, channel_number):
        exc = ConnectionError('Auto Reconnect Error')

        if not self._closing.done():
            self._closing.set_exception(exc)

        self._closing = create_future(loop=self.loop)
        self._futures.reject_all(exc)
        self._connection = connection
        self._channel_number = channel_number

        yield from self.initialize()

        for name, exchange in self._exchanges.items():
            yield from exchange.on_reconnect(self)

        for name, queue in self._queues.items():
            yield from queue.on_reconnect(self)
```

In that case, would it be better to add a check (or await?) on the connection before trying to recreate a channel?
