### ISSUE TITLE
'passive' param is not accepted by 'Channel.declare_exchange()'

### ISSUE THREAD

**Issue by pierec** [mosquito/aio-pika#72]
Is there a reason why `passive` param is not supported while declaring an exchange? It should just be a matter of passing another param to PIKA method (http://pika.readthedocs.io/en/0.10.0/modules/channel.html#pika.channel.Channel.exchange_declare).

I have a case where I'd like to bail out if the exchange does not exist already instead of attempting to create one.

I'd be more than happy to contribute a patch that fixes this issue, but wanted to consult here first :).

**Comment by mosquito** [comment]
I already released `1.5.1`
