### ISSUE TITLE
Publish to unexistent queue

### ISSUE THREAD

**Issue by olexandr-klymenko** [mosquito/aio-pika#78]
Exchange.publish doesn't seem to handle unexistent queue. So, if message is published request hangs forever. There should be a way to figure out that the queue is absent ant raise corresponding exception

**Comment by olexandr-klymenko** [comment]
for instance: nameko raises nameko.exceptions.UnknownService in this case

**Comment by mosquito** [comment]
For asynchronous mode you don't known when message will be message returned.

Simple solution: For process the returned messages you might add callback through `Channel.add_on_return_callback`

Complex solution: when you want to implement RPC-like pattern try to use [rabbitmq AE extension](https://www.rabbitmq.com/ae.html).

**Comment by mosquito** [comment]
I went deeper to the kombu sources and already find simple solution. Since `aio-pika 1.6.0` you might create the channel with `on_return_raises=True` argument (and the `publisher_confirms=True` of course).
