### ISSUE TITLE
how to use aio-pika in tornado?

### ISSUE THREAD

**Issue by calJ2016** [mosquito/aio-pika#81]
hello, could you give some example to show how to use aio-pika in tornado? thanks!

**Comment by elyssonmr** [comment]
I'm planning to migrate a project to aio-pika too. Currently I am using TorStomp.

As soon as possible I am going to share my experience.

**Comment by mosquito** [comment]
If you use tornado event_loop adapter it's simple.

```python

import asyncio
from tornado.ioloop import IOLoop

IOLoop.configure('tornado.platform.asyncio.AsyncIOLoop')
io_loop = IOLoop.current()
asyncio.set_event_loop(io_loop.asyncio_loop)

io_loop.start()
```

**Comment by mosquito** [comment]
[Example](http://aio-pika.readthedocs.io/en/latest/#tornado-example) added.
