### ISSUE TITLE
bug found: routing_key not work

### ISSUE THREAD

**Issue by Pro-YY** [mosquito/aio-pika#82]
in publish example: i.e.
publisher publish to a exchange with routing key, and subscriber bind queue and exchange with routing key.
It shows that routing_key takes no effect and turn out to be error, when **the 'queue name' is not the same as 'routing key name'**, hope fix in the future.

**Comment by mosquito** [comment]
aio-pika is the library which wrapping standard rabbitmq interface. I tested only wrapped functions. I guess you do something wrong with AMQP configuration. But provided information not enough.
