### ISSUE TITLE
Use asyncio.TimeoutError instead of TimeoutError

### ISSUE THREAD

**Issue by decaz** [mosquito/aio-pika#84]
I think that would be more appropriate solution.

**Comment by mosquito** [comment]
Why?

**Comment by decaz** [comment]
@mosquito from the experience of existing libraries. For instance:
- https://github.com/aio-libs/aiopg/search?q=TimeoutError
- https://github.com/aio-libs/aioredis/search?q=TimeoutError

In that case there will be not need to try to catch both `TimeoutError` and `asyncio.TimeoutError`.

**Comment by decaz** [comment]
@mosquito thanks! I see it was implemented in `1.8.0`. Can we close the issue now?

**Comment by decaz** [comment]
@mosquito ping.
