### ISSUE TITLE
Package versioning is handled incorrectly.

### ISSUE THREAD

**Issue by xlevus** [mosquito/aio-pika#89]
The way you're handling your package requirements is wrong (as far as I understand it).

Adding package dependencies based on python version should be handled like so:
https://github.com/python/mypy/blob/master/setup.py#L115

Adding dependency of python version should be handled like so:
https://github.com/xlevus/python-diana/blob/async-params/setup.py#L29

**Comment by xlevus** [comment]
I have spent the last 5 or so hours trying to work out why my `mypy` linting is broken.

Turns out, some cache somewhere got poisoned with a version of 1.7.3 that required the `typing` package despite using Python 3.6.2.

**Comment by mosquito** [comment]
Thank you for this useful recipes.
