### ISSUE TITLE
aiopika to aio-libs?

### ISSUE THREAD

**Issue by decaz** [mosquito/aio-pika#96]
I suggest to rename the project to `aiopika` and (maybe) move the repository to the https://github.com/aio-libs organization. It would be more pythonic relatively to other `asyncio` libraries and perhaps bring more users, testers, developers and contributors to the project.

@mosquito what do you think about it?

**Comment by mosquito** [comment]
I talked with @asvetlov two year ago. He explained me that move to the `aio-libs` it's more for PR then for the projects improvement.

That's works for reincarnate abandoned or orphaned projects too.

May be something changes.

**Comment by decaz** [comment]
Hmm.. interesting. I used to think that `aio-libs` is something like a hub for `asyncio` based projects.

And what about renaming the project? For backward compatibility, package with the old name `aio-pika` can remain with the version that is actual at the time of renaming (with description about rename), but package with new name `aiopika` will get further updates.
