### ISSUE TITLE
RobustChannel does not reset it's delivery-tag after reconnect.

### ISSUE THREAD

**Issue by xlevus** [mosquito/aio-pika#98]
I may be wrong here, I'm not 100% sure on how clients should handle this.

Given I have a RobustConnection, with a channel, and a non-durable, auto-delete queue, and one consumer. All flags are the default.

I can happily publish a messages to the queue.

When I restart rabbit, causing the connection to disconnect, once the connection has recovered, publishing a message results in

```
2018-01-24 14:45:25 [info     ] Unknown delivery tag 1 for message confirmation "Basic.Ack" [aio_pika.channel]
```
Additionally, once an unknown delivery tag is found, consumers using that channel no longer appear to consume.

the issue resolves itself by adding `self._delivery_tag = 0` to `Channel.initalize`.

**Comment by mosquito** [comment]
Thank you. This type of bugs which are so difficult to find.

**Comment by xlevus** [comment]
Thanks for the prompt resolution :+1:

**Comment by elyssonmr** [comment]
I think I have same issue. Checking if it resolves my problem :)
