### ISSUE TITLE
Support the amqps:// URL scheme

### ISSUE THREAD

**Issue by fmang** [mosquito/aio-pika#99]
I noticed that while aio-pika accepted URL in its connect functions, the scheme is ignored.

For example:

```python
connection = await aio_pika.connect('amqps://localhost/')
```

What it does: connect to localhost:5672, without SSL.

What it should do: connect to localhost:5671, with SSL.

Pika already implement that logic with the [URLParameters](https://github.com/pika/pika/blob/66387744cf971ebb1c69cf48b7de017f40ff9bbe/pika/connection.py#L711) class, so it might be a good idea to delegate the URL parsing functionality to it, and ensure aio-pika's URLs are consistent with pika's.

**Comment by mosquito** [comment]
[This example](https://pika.readthedocs.io/en/latest/examples/tls_mutual_authentication.html#tls-parameters-example) so useful for configure TLS options.

I guess in case of url-schema you have to pass `ssl_options` as a query string params.

Actually I never tried to connect through TLS before. 😅

**Comment by fmang** [comment]
aio-pika does work with TLS, by specifying the right parameters, but that's not the issue.

The amqps scheme is [officially defined](https://www.rabbitmq.com/uri-spec.html) by RabbitMQ, and pika supports it. When I migrated my code from pika to aio-pika, I was surprised TLS got disabled silently because aio-pika ignored the scheme.

aio-pika should at least raise an exception when the scheme is not amqp (or amqps when it supports it).

**Comment by mosquito** [comment]
@fmang could you please test the version 2.8.1?

**Comment by fmang** [comment]
> @fmang could you please test the version 2.8.1?

Sorry, I don't have the setup to test it anymore.
